build.gradle
This PR has the following updates
- simplify the `createChecksum` task by
- using FQN for its task type
- adding explicit dependsOn in task configuration
- using `distZip.destinationDir` as `outputDir`
- simplify `homebrew` task by
- adding explicit dependsOn in task configuration
- define an input.property on the project's version (reduces up-to-date misses)
- delay read of sha256 file until the very last moment, once filename has been written
=> Configuere checksum & homebrew tasks

examples/inetTest.java
Forked idea from: https://github.com/thoeni/inetTester
example script to measure time to resolve local hostname. Incorrectly configured `/etc/hosts` on Linux can cause slow JVM startup for server frameworks.
=> inetTest - measure time taken in ms to resolve localhostname.

examples/smee.java
It's a really minor change and not important at all but
I just think it's a cleaner way of waiting around than
writing an endless loop with waits.
=> Minor change in the way the smee example stays running

examples/urldep.java, readme.adoc, src/main/java/dk/xam/jbang/DependencyUtil.java, src/main/java/dk/xam/jbang/JitPackUtil.java, src/test/java/dk/xam/jbang/DependencyResolverTest.java, src/test/java/dk/xam/jbang/TestJitPack.java
You can now add URLs to repos from github.com, gitlab.com and bitbucket.org.
You can use links to the root of the master branch, to any tagged release or to a specific commit and they will be turned into GAV coordinates for JitPack. If the JitPack repo wasn't added by the developer it will be added automatically.
=> Adding jitpack support

src/main/java/dk/xam/jbang/DependencyUtil.java, src/test/java/dk/xam/jbang/DependencyResolverTest.java
Jbang is adding the same library multiple times on the classpath.
To reproduce:
```java
//usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.apache.commons:commons-configuration2:2.7
//DEPS org.apache.commons:commons-text:1.8
import org.apache.commons.configuration2.CompositeConfiguration;
import org.apache.commons.configuration2.SystemConfiguration;
import org.apache.commons.text.WordUtils;
public class commons {
public static void main(String... args) {
CompositeConfiguration config = new CompositeConfiguration();
config.addConfiguration(new SystemConfiguration());
System.out.println( WordUtils.capitalize("hello world"));
}
}
```
---
If you have a look at the same project with maven:
```xml
<dependencies>
<dependency>
<groupId>org.apache.commons</groupId> …
```
=> Prevent duplicate library on the classpath

src/main/java/dk/xam/jbang/DependencyUtil.java
For the line:
https://github.com/maxandersen/jbang/blob/bbd240c020f2a32830d450df3825348c7a9c4867/src/main/java/dk/xam/jbang/DependencyUtil.java#L66
Eclipse IDE is reporting following warning:
* **Description**: Unlikely argument type `String` for `contains(Object)` on a `Collection<MavenRepo>`
* **Resource**: DependencyUtil.java
* **Path**: /jbang/src/main/java/dk/xam/jbang
* **Location**: line 66
* **Type**: Java Problem
---
I think the static analysis is correct: `!repos.contains(REPO_JITPACK)` is always `true`.
I guess the idea was to not add the `jitpack` twice.
---
This PR contains a fix in this direction.
An alternative could be to remove the `&& !repos.contains(REPO_JITPACK)` part of the `if`.
=> Fix java warning

readme.adoc
A minor update to readme for showing icons when rendering on github. 
**Original:**
**With this change:**
=> docs: update github specific icons for asciidoctor syntax

build.gradle, readme.adoc, src/main/java/dk/xam/jbang/Main.java, src/main/java/dk/xam/jbang/Util.java, src/test/java/dk/xam/jbang/TestMain.java
This lets you do:
`jbang https://twitter.com/maxandersen/status/1266329490927616001`
and
`jbang https://carbon.now.sh/ae51bf967c98f31a13cba976903030d5`
Why:
* Because...sorry - no why besides because I can ?
This change addreses the need by:
* if url is exactly twitter.com or carbon.now.sh uses jsoup to parse
the downloaded html5 and look for `<meta property|name="og:description">` which luckily has the raw text of the tweet/code
* ...and then only if can find a `class XYZ ...static.*main` in that text
=> Add support for twitter and carbon url swizzling

src/main/scripts/container/Dockerfile, src/main/scripts/container/entrypoint.sh
The update allows jbang container to run as arbitary non root user. This makes it safe and comptaible to be run on OpenShift.
Fixes #119
=> (fix) run as non-root user

src/main/scripts/jbang.bat
JAVA_HOME on non english Windows System is usually on Path with Spaces inside like "C:\Program Files\OpenJDK\", so we need to quote them.
=> Quote JAVA_HOME for non english Windows.

src/main/java/dk/xam/jbang/Script.java, src/main/java/dk/xam/jbang/Settings.java, src/main/java/dk/xam/jbang/Util.java, src/main/java/dk/xam/jbang/cli/Alias.java, src/main/java/dk/xam/jbang/cli/BaseScriptCommand.java, src/main/java/dk/xam/jbang/cli/Edit.java, src/main/java/dk/xam/jbang/cli/Run.java, src/test/java/dk/xam/jbang/TestGrape.java, src/test/java/dk/xam/jbang/TestScript.java, src/test/java/dk/xam/jbang/cli/TestAlias.java, src/test/java/dk/xam/jbang/cli/TestEdit.java, src/test/java/dk/xam/jbang/cli/TestRun.java
You can now specify arguments and properties with aliases, just like with the `run` command. If you run an alias that has arguments and/or properties without specifying arguments and/or properties yourself then those arguments/properties will be used.
(depends on #144)
=> Extend aliases to store arguments and properties

src/main/java/dev/jbang/Settings.java
Older files will still be read and be automatically updated next time
a change has been made
=> The `alias.json` file now uses kebab naming

itests/quoting-win.feature, src/main/java/dev/jbang/cli/BaseCommand.java, src/main/java/dev/jbang/cli/Run.java, src/main/scripts/jbang.cmd, src/test/java/dev/jbang/cli/TestRun.java
Fixes #171. Quoting is now also a bit smarter, only quoting when necessary.
@maxandersen I tested this with the following command:
```
$ JBANG_CACHE_DIR=/tmp/jbang\ cache\ test ./build/install/jbang/bin/jbang echo.java test
```
But I'm not sure how to add that to Karate, so we're still missing a test for this.
=> Now quoting all arguments generated by Jbang before passing on to bash/cmd

src/main/java/dev/jbang/AliasUtil.java, src/main/java/dev/jbang/Settings.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/BaseScriptCommand.java, src/main/java/dev/jbang/cli/Catalog.java, src/test/java/dev/jbang/cli/TestAlias.java, src/test/java/dev/jbang/cli/TestCatalog.java
Local aliases are now stored in `~/.jbang/jbang-catalog.json` as stated by the docs.
And moved a bunch of alias/catalog related classes and utility methods from Settings to AliasUtil. (Settings was holding a lot of things not directly related to settings)
=> Alias fix and refactor

src/main/java/dev/jbang/cli/Edit.java, src/test/java/dev/jbang/cli/TestEdit.java
Reverts jbangdev/jbang#176
this have broken --live=idea|code|emacs -nw as these are scripts launching separate process thus killing the watch
=> Revert "Fix watchservice take"

src/main/java/dev/jbang/JdkManager.java, src/main/java/dev/jbang/Util.java
This is a very simplistic implementation that allows the user to select
the vendor at install time by defining a `JBANG_JDK_VENDOR` env var.
For now it at least makes it possible for those people that really want this.
We should see if this , somewhat hidden, option warrants to be turned into a full-fledged feature.
But that will be a lot more work.
See #203
=> First stab at allowing Vendor selection.

readme.adoc
This is good as a link, since it links to example source. However there's a
rogue backtick preventing it from linking to the right place (it appends a
"%60" to the URL). Removing it makes the link work properly.
=> Remove rogue backtick preventing link from working

src/main/java/dev/jbang/AliasUtil.java, src/test/java/dev/jbang/cli/TestAlias.java
Very small fix that prevented pre-defined arguments (and properties) from working
=> Fixed aliases not picking up pre-defined arguments

itests/quoting-win.feature, itests/quoting.feature, src/main/java/dev/jbang/cli/Run.java, src/main/scripts/jbang.cmd, src/test/java/dev/jbang/cli/TestRun.java
Fixes #245 
So the fix for the spaces was simply the fact that spaces were not being escaped.
But the fact that the IT tests didn't work (anymore) was because we had turned on delayed expansion in the batch file. Turns out that having `!` in your command line on WIndows gives all kinds of trouble when you also have delayed expansion turned on. The `!` is basically unescapable so you need to turn delayed expansion off again just before running the jbang java command.
=> Fix for quoting, including spaces, on Windows

examples/resource.java, examples/resource.properties, src/main/java/dev/jbang/FileRef.java, src/main/java/dev/jbang/Script.java, src/main/java/dev/jbang/cli/Init.java, src/main/java/dev/jbang/cli/Run.java, src/test/java/dev/jbang/cli/TestRun.java
Supports `//FILES <relative path>[=<relative path>]`
meaning:
`//FILES resource.txt`
adds a file named `resource.txt`
`//FILES resource.txt=META-INF/application.properties`
This does not yet support:
- edit (files not handled thus just broken)
- files fetched from http(s) (no HttpFileSystemProvider)
- jsh (ignored)
Relates to #39
=> Add initial //FILES support for adding resuorces to app

src/main/java/dev/jbang/DeprecatedMessageHandler.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/Build.java, src/main/java/dev/jbang/cli/Cache.java, src/main/java/dev/jbang/cli/Catalog.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Init.java, src/main/java/dev/jbang/cli/Jbang.java, src/main/java/dev/jbang/cli/Jdk.java, src/main/java/dev/jbang/cli/Run.java, src/main/java/dev/jbang/cli/Trust.java, src/test/java/dev/jbang/cli/TestArguments.java
Implemented the grouping but not all sure about the grouping - feedback welcome:
```
Usage: jbang [-h] [--verbose] [COMMAND]
Compiles and runs .java/.jsh scripts.
-h, --help      Display help/info
--verbose   jbang will be verbose on what it does.
Basic Commands:
run         Compile and run provided .java/.jsh script.
edit        Edit a .java/.jsh script.
init        Initialize a .java/.jsh script.
Advanced Commands:
build       Build .java/.jsh script without running. Use for caching
dependencies.
trust       Manage trust domains.
cache       Cache management.
Catalog:
alias       Manage aliases.
catalog     Manage catalogs.
Other:
version     Display version info.
completion  Output auto-completion script for bash/zsh.
Usage: source <(jbang completion)
Copyright: 2020 Max Rydahl …
```
=> grouping of commands in help

CONTRIBUTING.adoc, readme.adoc
I read throught de contributing and readme docs to fix some typos and asciidoctor formatting.
I have avoided any major text changes other than some commas and minnor changes.
Also:
* Corrected kubectl plugins automatic casing example based on a test run in my machine. The docs say it generates  `KubectlMyPlugin` from `kubectl-myplugin` but it generates ` `KubectlMyplugin`. Not sure if maybe is better to use `kubectl-my-plugin` and keep `KubectlMyplugin` output?
There are two things which I had no clear how to fix:
1. The example in *Using `.jsh` for `jshell`* is not clear to me. Specially about how to pass properties.
Maybe should be replaced with something like
```java
System.out.println("Hello " + (args.length>0?args[0]:"World")); // <.>
System.out.println(System.getProperty("key"); // …
```
=> fix docs typos and asciidoctor styling

src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/Build.java, src/main/java/dev/jbang/cli/Run.java, src/test/java/dev/jbang/cli/TestRun.java
Didn't really like `Build` inheriting from `Run` because it seemed the wrong way around. So I created a common base class for them containing all the code necessary for `Build` and all of the build-related code for `Run`.
=> Move common code from `build` and `run` to common base class

readme.adoc, src/main/java/dev/jbang/cli/Edit.java
Currently you could only open editor automatically when using --live and often you don't need live as deps not changing. This change makes --live a boolean toggle and --open can now be used to open project in editor uniformly on all platforms.
BREAKING CHANGE: --live=[editor] will no longer work. Use `--open=[editor] --live` instead.
I'm not happy having to break users using --live but without an answer to 
https://groups.google.com/u/1/g/picocli/c/__tziJIw3lE I dont see a good way to fix it.
=> feat(edit): add `--open=[editor] and make --live a boolean

.gitignore, examples/NanoClock.java, examples/inetTest.java, itests/Two.java, itests/one.java, itests/run.feature, readme.adoc, src/main/java/dev/jbang/FileRef.java, src/main/java/dev/jbang/Script.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/Edit.java
Thie lets you use `//SOURCES <path>` with some restrictions:
1) the reference sources are not processed for //DEPS or any other jbang support (will come)
2) jbang edit does not undestand it yet.
3) No **/* matching. Thus each file must be explicit and relative to the file that refer to them.
=> feat: Initial support for multiple sources

src/main/java/dev/jbang/cli/Jdk.java
Before, if the JDK didn't exist, it would first nicely download the JDK
before deling it ;-)
=> fix: `jdk uninstall` now firsts checks if JDK exists

src/main/java/dev/jbang/JdkManager.java, src/main/java/dev/jbang/Util.java, src/main/java/dev/jbang/cli/BaseScriptCommand.java
`JdkManager.downloadAndInstall()` now restores better after an error.
`Util.downloadFile()` is now equally robust as the JDK downloader.
I noticed that interrupting a download could leave the cache in an unusable state unless first cleaned.
The JDK downloader was already very careful about first downloading to a temp location and only committing when the download finished correctly, but now the file downloader does this as well.
=> fix: made downloading more robust

readme.adoc, src/main/java/dev/jbang/JavaUtil.java, src/main/java/dev/jbang/JdkManager.java, src/main/java/dev/jbang/Settings.java, src/main/java/dev/jbang/Util.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Jdk.java, src/main/scripts/jbang, src/main/scripts/jbang.cmd
These commands were added to facilitate the use of the Jbang's JDKs
by the user. This way it's not necessary to install additional JDKs
if we want to use Java and have previously let Jbang install a JDK.
`jdk default` set the given JDK as "current".
`jdk home` returns the path of the current or the given JDK.
`jdk java-env` returns the shell commands to make the current or
the given JDK usable in the user's shell.
=> feat: Added `jdk default`, `jdk home` and `jdk java-env` commands 

itests/catalog.feature, itests/version.feature, src/main/java/dev/jbang/AliasUtil.java, src/main/java/dev/jbang/FileRef.java, src/main/java/dev/jbang/IntegrationManager.java, src/main/java/dev/jbang/JdkManager.java, src/main/java/dev/jbang/URLRef.java, src/main/java/dev/jbang/Util.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/BaseCommand.java, src/main/java/dev/jbang/cli/BaseScriptCommand.java, src/main/java/dev/jbang/cli/Build.java, src/main/java/dev/jbang/cli/Cache.java, src/main/java/dev/jbang/cli/Catalog.java, src/main/java/dev/jbang/cli/Completion.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Init.java, src/main/java/dev/jbang/cli/Jbang.java, src/main/java/dev/jbang/cli/Jdk.java, src/main/java/dev/jbang/cli/Run.java, src/main/java/dev/jbang/cli/Trust.java, src/main/java/dev/jbang/cli/Version.java, src/main/java/dev/jbang/cli/Wrapper.java, src/main/scripts/jbang, src/main/scripts/jbang.cmd
Before we would either print as much output to stderr, which is not
in line with the Rule of Least Surprise, or we had to print the output
as part of a shell command like `echo` or `cat`. Now we have a special
exit code that will tell the startup scripts to either execute Jbang's
output or to simply display it.
=> refactor: Now using special exit code to allow printing to stdout

CONTRIBUTING.adoc, readme.adoc
Use adoc based code listing in .adoc files, not md based
An example of diff
- https://github.com/jbangdev/jbang/blob/master/readme.adoc#declare-dependencies
- https://github.com/rsvoboda/jbang/blob/ascii.vs.md/readme.adoc#declare-dependencies
GH handles md style in .adoc quite well, but the will be issue once .adoc files get processed by other tools.
=> fix(doc): Use adoc based code listing, not md based

src/main/java/dev/jbang/cli/Alias.java
feat: add ansi coloring to alias list
Fixes https://github.com/jbangdev/jbang/issues/308
=> feat: add ansi coloring to alias list

src/main/scripts/jbang.cmd, src/main/scripts/jbang.ps1
`JBANG_USES_POWERSHELL=true` was set too late for Jbang to pick it up.
Fixes #401
=> fix: We now properly notify Jbang we're running in PowerShell

src/main/scripts/jbang.ps1
The instruction now show 2 alternatives, one is shorter but might
be somewhat less flexible while the other is somewht more verbose
but has the interesting property that you can store it in a variable
and re-use it.
=> docs: Some additional instructions for zero-install with PowerShell

itests/cache.feature, src/main/java/dev/jbang/Settings.java, src/main/java/dev/jbang/cli/Cache.java, src/main/scripts/jbang, src/main/scripts/jbang.cmd, src/main/scripts/jbang.ps1
NB: Needs to be merged after #402
refactor: The Jbang zero-install cache is now an official category
Instead of putting the Jbang zero-install download in `cache/urls`
it's now put in its own `jbang` directory. This means it won't be
deleted when doing a normal `cache clean`, just like the JDKs.
(It will still be deleted when explicitely mentioned or when using
`cache clear -all`).
See #396
=> refactor: The Jbang zero-install cache is now an official category

src/main/java/dev/jbang/Script.java, src/main/java/dev/jbang/cli/Run.java, src/test/java/dev/jbang/cli/TestRun.java
When running jars like org.eclipse.jgit:org.eclipse.jgit.pgm:5.9.0.202009080501-r we
got noclassdefounderrors since we need to put the dependencies in the classpath, but
with `-jar` java ignores the classpath.
Thus we need to simulate a -jar run instead.
note: this is technically a breaking change but i can not imagine anyone using -jar that worked before being affected by this change.
=> fix: stop using -jar

readme.adoc
Fix a heading tag that had a + instead of a =
=> doc: fix header typo

src/main/java/dev/jbang/cli/Build.java, src/main/scripts/jbang, src/main/scripts/jbang.cmd
The jbang.cmd script wasn't handling the creation
of temp files correctly. Also the *nix verion of
the script wasn't properly detecting runing on
Cygwin anymore either. Both are now fixed.
Fixes: #421
=> fix: Windows testing broken

src/main/java/dev/jbang/cli/Edit.java
This makes the CLI impossible to quit in Fedora 32.
Fixes #407
=> Remove interactive flag from sh

src/main/java/dev/jbang/cli/Init.java
Fixes #310
example:
```shell
❯ jbang init t.java
[jbang] File initialized. You can now run it with 'jbang t.java' or edit it using 'jbang edit --open=idea t.java`'
❯ jbang init t2.java
[jbang] File initialized. You can now run it with 'jbang t2.java' or edit it using 'jbang edit --open=code t2.java`'
❯ jbang init t3.java
[jbang] File initialized. You can now run it with 'jbang t3.java' or edit it using 'jbang edit --open=code t3.java`'
❯ jbang init t4.java
[jbang] File initialized. You can now run it with 'jbang t4.java' or edit it using 'jbang edit --open=eclipse t4.java`'
❯ jbang init t5.java
[jbang] File initialized. You can now run it with 'jbang t5.java' or edit it using 'jbang edit --open=netbeans t5.java`'
```
=> fix: have random edit examples for jbang init

src/main/scripts/jbang
Using MSYS2 in Windows causes uname -s returns a string like: MSYS_NT-10.0-19041
Added MSYS* to case statement so that using MSYS2 is detected as Windows.
This is a fix for the issue I created here: https://github.com/jbangdev/jbang/issues/452
=> fix: allow MSYS2 to pass OS check in jbang script

src/main/scripts/jbang
Added Raspberry Pi armv7l architecture (arm) to the list of known architecture for download.
Raspberry Pi OS come without java installed, and with this addition to the architecture "list" jbang can auto download java.
I have tested with helloworld.java from the example dir on my Pi with fresh Raspberry Pi OS.
=> feat: Added support downloading JDK if not found on Raspberry Pi

readme.adoc
This changes adds a new FAQ section for automated configuration tool support. Currently I've only added `clang-format` as that's what I'm currently using, but we can expand this with more tool settings going forward.
=> docs: Add clang-format formatting settings to FAQ

src/main/java/dev/jbang/TrustedSources.java, src/main/java/dev/jbang/cli/BaseScriptCommand.java, src/main/java/dev/jbang/cli/Trust.java, src/test/java/dev/jbang/TestScript.java
This PR fixes the error below:
```java
./jbang/bin/jbang --verbose https://gist.github.com/tivrfoa/8e6ea001f168fd4ef14763ceca3e5ab6#file-one-java
[jbang] Gist url api: https://api.github.com/gists/8e6ea001f168fd4ef14763ceca3e5ab6
[jbang] Downloaded file https://gist.githubusercontent.com/tivrfoa/8e6ea001f168fd4ef14763ceca3e5ab6/raw/f378d987f0f863d0b3bcecce1c91fa4290ec4816/one.java
[jbang] Gist url api: https://gist.github.com/tivrfoa/two.java
[jbang] Error when extracting file from gist url.
[jbang] [ERROR] java.io.FileNotFoundException: https://gist.github.com/tivrfoa/two.java
```
ScriptResource.originalSource has the value after swizzleURL, and that's important to find the other sources.
=> fix: original source must be what's in ScriptResource.originalSource

src/main/java/dev/jbang/cli/BaseScriptCommand.java, src/test/java/dev/jbang/TestSameSourceInDifferentPaths.java, src/test/java/dev/jbang/TestSourcesMutualDependency.java
This PR fixes the logic that checks if a source was already visited.
Today it considers exactly how it's declared in the //SOURCES
eg: `//SOURCES model/C`
So in the scenario below:
```
.
├── A.java
├── model
│   └── C.java
└── person
├── B.java
└── model
└── C.java
```
This error happens:
```java
/home/leandro/dev/java/jbang/scripts/test-multiple-child-folders-package/person/B.java:5: error: package person.model does not exist
import person.model.C;
```
So the solution is to check if the full resolved path was already visited.
And why is the visited logic needed? What can go wrong if it's removed?
Two reasons:
1. It avoids doing redundant work;
2. It avoids a possible infinite loop if there's a mutual dependency
eg:
Main.java
```java
//SOURCES A.java
public class Main {
public static void …
```
=> fix: it must allow same //SOURCES in different paths

src/main/java/dev/jbang/ArtifactInfo.java, src/main/java/dev/jbang/Script.java, src/test/java/dev/jbang/cli/TestRun.java
Can now do `jbang https://bintray.com/cardillo/maven/download_file?file_path=joinery%2Fjoinery-dataframe%2F1.9%2Fjoinery-dataframe-1.9-jar-with-dependencies.jar`
without it resolving bad classpath.
Fixes #490
=> feat: run jar from a https url

readme.adoc
Just a minor thing.
It's because I copied and pasted and got the error:
```
./A.java 
./A.java: line 1: syntax error near unexpected token `('
./A.java: line 1: `///usr/bin/env jbang "$0" "$@" ; exit $? // (1)'
```
Changing it to shell comment it works.
wdyt?
=> fix: use shell comment in direct run example

src/main/java/dev/jbang/cli/BaseBuildCommand.java
Just a minor refactor so it's easier to have `build()` clean up after itself.
It now deletes the directory with sources that was used to compile and create the JAR file.
=> refactor: `build()` now cleans up after itself

readme.adoc
This wasn't super obvious to me at first and took me a second to figure out - perhaps it's useful to explicitly document this here.
If there is an easier way, especially e.g. for Fedora users, let's add that here as well? (What was that GraalVM distribution from Red Hat again?)
=> docs: Clarify how to install the native-image utility binary

.github/workflows/ci-build.yml
The ci-build / build-and-testing job is failing at add-to-path because the ::add-path:: is now disabled.
See #519
=> fix(#519): Fix disabled ::add-path:: command in ci-build

src/main/resources/build.qute.gradle, src/test/java/dev/jbang/cli/TestEdit.java
Without the support of `gradle run`, first users could be a little bit disappointed if they are used to execute:
Or if in the terminal of their IDE they try `./gradlew run` instead of `./gradlew build`
The fix also removes redundant tabs in `build.gradle`.
**Before**
```
apply plugin: 'java'
repositories {
mavenLocal()
jcenter()
}
dependencies {
compile "org.openjfx:javafx-graphics:11.0.2"
}
sourceSets.main.java.srcDirs 'src'
sourceSets.test.java.srcDirs 'src'
```
**After**
```
plugins {
id 'java'
id 'application'
}
repositories {
mavenLocal()
jcenter()
}
dependencies {
compile "org.openjfx:javafx-graphics:11.0.2"
}
application {
mainClass = 'edit'
}
sourceSets.main.java.srcDirs 'src'
sourceSets.test.java.srcDirs 'src'
```
=> fix(#18): enable gradle run

readme.adoc
fixes #506
also mentions no native image support for .jsh (re. #510)
=> docs: Clarify that .jsh are not cached and no native support (fixes #506)

src/main/java/dev/jbang/cli/Run.java, src/test/java/dev/jbang/cli/TestRun.java
It uses @argument file if it's Windows and Java version >= 9
fixes #476
=> fix: long classpath problem on Windows

itests/jsh.feature, src/main/java/dev/jbang/Script.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/Run.java, src/test/java/dev/jbang/cli/TestRun.java
- error instead of 'null' when --native is used.
- don't fail on empty .jsh when doing --interactive
=> Fixes two jsh issues

readme.adoc
with the `-useb` (short for `-UseBasicParsing`) we can make sure that it will always run correctly
=> docs: Make sure zero-install on Windows always works

src/main/java/dev/jbang/cli/Init.java
Fixes #551
Now `jbang init test2.java` prints: 
`[jbang] File initialized. You can now run it with 'jbang test2.java' or edit it using 'jbang edit --open=[editor] test2.java' where [editor] is your editor or IDE, e.g. 'code'`
the editor is one of the known supported ones (code, idea, eclipse, etc.)
ok or too short ?
=> fix: attempt of a more explicit edit message

build.gradle
It results in a broken jboss-logging that can't be
used with Quarkus.
=> fix: Don't attempt to minimse jboss-logging

src/main/scripts/jbang.ps1
=> fix: PowerShell zero-install now works again

src/main/java/dev/jbang/cli/Edit.java
Fix for running `edit --live` but with an absolute path to the script.
Without this fix, "changed" is a relative path, which then turns out to not exist.
=> fix: watchService's event is relative to watched directory

readme.adoc, src/main/java/dev/jbang/JitPackUtil.java, src/test/java/dev/jbang/TestJitPack.java
Fixes #564
instead of defaulting to master  we use HEAD which should get us latest and greatest.
=> fix: jitpack no long assumes default branch is master

readme.adoc
Minor typo fix for script output in readme.adoc
The script will have the output:
```
Hello World
value
```
=> docs: Add missing System.out.println for properties in readme.adoc

src/main/java/dev/jbang/AliasUtil.java, src/main/java/dev/jbang/ModularClassPath.java, src/main/java/dev/jbang/Script.java, src/main/java/dev/jbang/Util.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/BaseScriptCommand.java, src/main/java/dev/jbang/cli/Build.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Export.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/cli/Jbang.java, src/main/java/dev/jbang/cli/Run.java, src/test/java/dev/jbang/cli/TestRun.java
This has become a bit of a mix of related changes. The 2 main features are:
1. get a copy of the script JAR by specifying ~`--output` / `-O`~ `jbang export <script-ref>`
But that JAR won't work without setting up all the necessary deps, so:
2. add dependencies to the JAR manifest so the JAR can simply be executed with `java -jar` **on the same system**. (It won't work on other computers, but it also won't hurt)
3. There was already code for setting Boot-Class-Path but it was using the wrong format, so fixed that while adding 2. 
4. Refactored the Script object to make it stateless which was a change I had lying around for weeks already and given the fact that these changes used that exact same code I decided to add it in the PR.
=> Jar output via jbang export

readme.adoc
incorrect:
```jbang -Dkey=value World helloworld.jsh```
correct:
```jbang -Dkey=value helloworld.jsh World```
The incorrect command produces the following output:
```
[jbang] [ERROR] Could not read script argument World
[jbang] Run with --verbose for more details
```
=> docs: Fix documentation error in readme.adoc

itests/hellojsh, itests/jsh.feature, src/main/java/dev/jbang/Script.java, src/main/java/dev/jbang/Util.java, src/main/java/dev/jbang/cli/BaseScriptCommand.java, src/main/java/dev/jbang/cli/Run.java
Main usecase is that tools like bach uses suffix less files.
for example to allow building https://github.com/jbee/purejin
using `jbang --jsh --java 16 https://bit.ly/bach-main-build`
=> feat: --jsh to allow forcing .jsh

itests/kubectl-example, src/main/java/dev/jbang/cli/App.java, src/test/java/dev/jbang/cli/TestApp.java
i.e. `kubectl-example` stays `kubectl-example` not kebabified `KubectlExample`
Fixes #653
=> fix: have app install use better derived name

readme.adoc
Added explanation how to install Jbang using Jbang is the first option, thereby promoting the option that has no additional dependencies on package managers that are not available by default on the user's system.
=> docs: Jbang install option

src/main/java/dev/jbang/Util.java
This adds the `-` to the Gist regex as Github user names - such as mine - can contain dashes.
=> bug: Fix gist regex to handle usernames with hyphens

src/main/java/dev/jbang/AliasUtil.java, src/main/java/dev/jbang/Script.java, src/main/java/dev/jbang/cli/Alias.java, src/test/java/dev/jbang/cli/TestAlias.java
A proposition that fixes #190.
Support of multiple tag DESCRIPTION that creates a merged description.
The description in argument has more precedence than the DESCRIPTION tag in the script.
=> feat: add //DESCRIPTION tag in scripts

build.gradle, readme.adoc, src/main/java/dev/jbang/DependencyUtil.java, src/test/java/dev/jbang/DependencyResolverTest.java
jbang will now if and only if the very first dependency has a `@pom`
classifier, download it and load it as pom file in shrinkwrap.
Example:
```java
//DEPS io.quarkus:quarkus-bom:1.11.0.Final@pom
//DEPS io.quarkus:quarkus-resteasy
//DEPS io.quarkus:quarkus-smallrye-openapi
//DEPS io.quarkus:quarkus-swagger-ui
```
Then that pom file dependency management (and dependencies) gets listened to.
Fixes #63
Caveats:
- I would prefer if could load arbitrary amount of bom/pom's but I haven't found
a way to do that with shrinkwrap; we could potentially if more than one found generate
a temporary one that has them all listed (TBD)
- This also means that we can't support the sequence being arbitrary; basically @pom's has to come first
Should add check that for now is only *one* @pom and reject …
=> feat: support for BOM POM's i.e. maven dependencyManagement

src/main/java/dev/jbang/Util.java, src/test/java/dev/jbang/TestUtil.java
Fixes #693
This is not a true fix that will work in all situations. It for example still assumes that `filename` will be the last item in the `Content-Disposition` string, which although almost always true is not really something that the spec requires. A fool proof implementation would be much more complex however so we either we merge this until something better is needed or we just throw this away and add the code linked in the issue. It's up to you @maxandersen :-)
=> fix: Simplistic fix for encoded Content-Disposition

src/main/java/dev/jbang/JarSource.java, src/main/java/dev/jbang/ScriptSource.java, src/main/java/dev/jbang/Source.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java
The first commit is simple:
The script's classpath was already stored in the JAR but we extracted it only in the specific place where it was needed. The `JarSource` now takes care of extracting that information.
This also cleans up the usage of MANIFEST attribute names a bit.
The second commit is a bit trickier:
The script's JAR is now used exclusively when it exists. Before Jbang would still parse the script file for information about dependencies and options, but those are also stored in the JAR itself so we should skip that and just use the JAR. Which is what this commit does. It also allows us the remove that "specific place" mentioned above.
=> Jar classpath + cleanup

src/main/java/dev/jbang/DecoratedSource.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/BaseScriptDepsCommand.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Info.java, src/test/java/dev/jbang/cli/TestInfo.java
It's a minor change which adds the flags `--deps` and `--cp` to the `info` and `edit` commands.
It's especially useful for `info` where we can add extra dependencies using `--deps`. The `--cp` is perhaps less useful but it's just to be complete.
The same for `edit`, not sure if these options are very useful for it, but it uses the same kind of code that `info` does, so just to be complete I've added the options there too.
=> feat: `--deps` and `--cp` now available on `info` and `edit`

src/main/java/dev/jbang/DependencyUtil.java, src/main/java/dev/jbang/EditorManager.java, src/main/java/dev/jbang/JdkManager.java, src/main/java/dev/jbang/ResourceRef.java, src/main/java/dev/jbang/ScriptSource.java, src/main/java/dev/jbang/TemplateEngine.java, src/main/java/dev/jbang/cli/App.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/DeprecatedMessageHandler.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/cli/Jbang.java, src/main/java/dev/jbang/cli/StrictParameterPreprocessor.java, src/main/java/dev/jbang/cli/VersionProvider.java, src/main/java/dev/jbang/spi/IntegrationManager.java, src/main/java/dev/jbang/spi/IntegrationResult.java, src/main/java/dev/jbang/util/ConsoleInput.java, src/main/java/dev/jbang/util/ConsoleInputReadTask.java, src/main/java/dev/jbang/util/JarUtil.java, src/main/java/dev/jbang/util/PropertiesValueResolver.java, src/main/java/dev/jbang/util/UnpackUtil.java, src/test/java/dev/jbang/DependencyResolverTest.java, src/test/java/dev/jbang/TestSourcesRecursivelyMultipleFiles.java, src/test/java/dev/jbang/TestUtil.java, src/test/java/dev/jbang/cli/TestApp.java, src/test/java/dev/jbang/cli/TestRun.java
eclipse cleanup + some intial basic package splits.
spi - service provider interface
util - classes that are truly util (some left named util but they are more things that porbably should be on the actual thing)
cli - old package but some classes was wrongly put in dev.jbang
=> chore: remove unsed code and warnings in eclipse and package setup

src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/dependencies/ModularClassPath.java, src/main/java/dev/jbang/source/RunContext.java, src/test/java/dev/jbang/cli/TestRun.java, src/test/java/dev/jbang/dependencies/DependencyResolverTest.java
Fixes #707
Dumb mistake. I should have double-checked.
If possible I'd do a quick-fix release @maxandersen . It's not _that_ bad , but I don't want people depending on this "feature" and then later complain it got broken :-)
To explain that better: right now you could do `jbang run --dep fu:bar:1.0 myfile.java`  and also `java -jar .../path/to/myfile.java.jar` and that would work.... but it shouldn't. The `--dep` is for adding dependencies at runtime, it shouldn't be "baked in".
But of course people might think it's very useful, you could have provided a whole bunch of deps at compile time but at runtime you don't have to anymore, yay! No! Not yay! :-)
It goes back to the idea of being able to use service loaders etc, it must be possible to specify deps at runtime for that.
Sorry for the …
=> fix: jbang doesn't store additional deps in JAR Class-Path anymore

build.gradle, readme.adoc, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/cli/TestEdit.java, src/test/java/dev/jbang/util/TestUtil.java
Please delete this text, and add description of the topic solved by this PR.
To make releases as automated as possible we use conventional commits formats.
Thus commits and pull-requests titles should before merge follow the Conventional Commits spec.
Details in https://github.com/zeke/semantic-pull-requests
If in doubt then open the pull-request and we'll help you - Thank you!
-->
=> fix: move to use mavencentral instead of jcenter

.github/workflows/publish-packages.yml, misc/promotesnap.sh
This adds tag update of jbang-snap which will trigger
a build on snapcraft visible at https://snapcraft.io/jbang/builds
Then we wait ~20 minutes before we do a scripted promote
of every builds with the same version as we tagged with.
We do it this way as snapcraft for reasons I just don't grok
do not want to enable automated releases..so we have to work our
way around it.
=> chore: enable build and promotion of snapcraft

src/main/java/dev/jbang/source/JarSource.java, src/main/java/dev/jbang/source/RunContext.java, src/main/java/dev/jbang/source/ScriptSource.java, src/test/java/dev/jbang/cli/TestInfo.java
A JarSource that is created from a ScriptSource should have the
same backingResource as the original ScriptSource.
Fixes #734
=> fix: Using correct backingResoure for JarSources

readme.adoc
The current instructions actually resulted in a warning message saying jbang was already installed.
This is because the zero-install procedure already copies the jbang scripts+jar to the same place that `app install` does.
The only thing that's needed is the `app setup` which will make the required changes to the user's PATH.
=> docs: Fixed "Using Jbang" installation instructions

src/main/java/dev/jbang/cli/App.java
This would happen when there was nothing to be done but we still
returned with the exit code instructing the startup script to
execute jbang's output.
=> fix: No longer showing ugly error after `app setup`

src/main/scripts/jbang
Was originally tested in an unclean test environment which hid
the problem of performing a zero-install run on Windows when
using Cygwin/GitBash/etc
Fixes #746
=> fix: jbang-native setup on Windows

src/main/java/dev/jbang/source/ResourceRef.java, src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/source/TestSourcesMultipleSomeMissingFiles.java
//SOURCE missingfile.java will now error.
//SOURCE **/*.java and it matches symoblic link which point to dead file will be ignored
@quintesse should we maybe ignore both cases and just print warn during --verbose ? WDYT?
=> fix: ignore dead symbolic links and fail on explicit missing //SOURCE (#744)f

src/main/java/dev/jbang/util/Util.java, src/main/scripts/jbang
This PR (Only about two months after I told @maxandersen I'd do it!) adds support for IBM's AIX:
- Detection of `os` and `arch` variables
- Removal of dependency on GNU tar for `--strip-components` parameter (Similar logic to macos is now used everywhere
Alternatives considered:
- Detect whether GNU tar is present and use the `--strip-components` parameter if it is, otherwise use the alternate mechanism
- Using a weird regex to see if `uname -m` is a hex string and if so assume AIX
- Use uname -p on AIX to set `arch`
Also worth noting that this does still rely on `readline` which isn't standard on AIX but can be obtained from e.g. the `coreutils` package on the AIX toolbox
=> Add support for running jbang on AIX (also removes GNU tar dependency)

src/main/java/dev/jbang/dependencies/ArtifactInfo.java, src/main/java/dev/jbang/dependencies/DependencyCache.java, src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/dependencies/ModularClassPath.java, src/main/java/dev/jbang/source/JarSource.java, src/main/java/dev/jbang/source/ResourceRef.java, src/main/java/dev/jbang/source/ScriptSource.java, src/main/java/dev/jbang/spi/IntegrationManager.java, src/test/java/dev/jbang/dependencies/DependencyResolverTest.java, src/test/java/dev/jbang/dependencies/TestArtifactInfo.java
Updating the dependency cache now correctly only writes out the
information that was actually retrieved and updated. Before the
code would always write out the latest timestamps, updating them
for *all* files in the cache, even the ones we weren't even
retrieving. Because resolving dependencies is a multi-step
process this basically ruined the information that was needed
for the following steps.
Fixes #757
=> fix: Now correctly handles out-of-date dependencies

src/main/scripts/jbang, src/main/scripts/jbang.ps1
Today while using Jbang on Windows I found out that the hand-off from the bash script (running in Git Bash) to the .cmd file wasn't taking into account quoted arguments.
So something like `jbang hello@jbangdev one "two three"` would display:
```
Hello one
Hello two
Hello three
```
After fixing that I went on to check if other hand-offs had similar problems and indeed, running `curl -Ls https://sh.jbang.dev | bash -s - hello@jbangdev one "two three"` gave the same problem (both on Linux as on Windows).
So the second commit fixes that.
=> Fix quoting in jbang startup scripts

src/main/java/dev/jbang/dependencies/JitPackUtil.java, src/test/java/dev/jbang/dependencies/TestJitPack.java
HEAD-SNAPSHOT does not seem to work with jitpack thus moving to use -SNAPSHOT instead
Fixes #766
=> fix: make git urls work with jitpack again

readme.adoc, src/main/java/dev/jbang/cli/Run.java, src/test/java/dev/jbang/cli/TestRun.java
Implementing this revealed lots of our tests relied on 
jbang ignoring no main class found and just added the java
file as argument blindly.
Thats why there is alot of "fakemain" being added to tests so they 
dont fail now that --interactive means no arguments must be passed.
Fixes #112
=> feat: add interactive mode for non-jshell

src/main/java/dev/jbang/cli/Edit.java
Affects all Operating systems.
Now forcefully escape launched editor.
Fix #798
=> fix: be able to launch editors with space in name

itests/java4321.java, itests/javaversion.feature, src/main/java/dev/jbang/cli/Build.java, src/main/java/dev/jbang/cli/Export.java, src/main/java/dev/jbang/cli/Run.java, src/main/java/dev/jbang/source/RunContext.java
=> fix: build and runtime not following same java version. fixes 806

readme.adoc
Adds the jbang-maven-plugin and the Gradle plugin as alternatives for running JBang scripts
=> docs: Add Maven and Gradle Plugins to readme.adoc

readme.adoc
`jbang list` and `jbang uninstall` require the use of the `app` command.
=> docs: fix usages of app subcommand

src/main/java/dev/jbang/cli/Jdk.java
=> fix: `jdk home` output won't print "echo" anymore

src/main/java/dev/jbang/catalog/Catalog.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/source/ResourceRef.java
The `alias list` command wasn't showing the `@catalogname` in the appropriate circumstances giving the impression that you could run the alias simply by using it's name (which in case of the implicit catalogs isn't the case).
=> chore: Alias list again shows @ catalog where appropriate

src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/source/JarSource.java, src/main/java/dev/jbang/source/RunContext.java, src/main/java/dev/jbang/source/ScriptSource.java, src/main/java/dev/jbang/source/Source.java
Fixes #833
Eg:
```json
$ jbang info tools itests/resource.java
{
"originalResource": "itests/resource.java",
"backingResource": "/home/tschotan/projects/jbang/jbang/itests/resource.java",
"applicationJar": "/home/tschotan/.jbang/cache/jars/resource.java.dd614e274e05a4b3e200963f43ba65e8ee416d7a0955957a1cc93f6f7c7cd224.jar",
"resolvedDependencies": [],
"availableJdkPath": "/home/tschotan/.sdkman/candidates/java/current",
"files": [
{
"originalResource": "itests/resource.properties",
"backingResource": "/home/tschotan/projects/jbang/jbang/itests/resource.properties"
},
{
"originalResource": "itests/resource.properties",
"backingResource": "/home/tschotan/projects/jbang/jbang/itests/resource.properties",
"target": "renamed.properties"
},
{
"originalResource": "itests/resource.properties", …
```
=> feat: `info tools` now returns a lot more information

src/main/java/dev/jbang/cli/App.java, src/main/scripts/jbang.cmd, src/main/scripts/jbang.ps1
When a new update gets downloaded we won't try to overwrite
the jbang.jar on Windows because that would fail anyway.
Instead we copy the new jar next to the old jar as `jbang.jar.new`
and we overwrite the old version when the user runs jbang the
next time.
Fixes #823
=> fix: Update should now work on Windows

readme.adoc
The version in the old url is still 24
=> docs:Fix the fedora corp url

src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/Run.java
We now correctly quote the first CLI argument as well as all the
arguments in the @-file. We also take into account now the values
of //JAVA and --java when determining which Java version we're
running.
Fixes #874
=> fix: Correct use of @-files

CONTRIBUTING.adoc, readme.adoc, src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/source/TestSourcesMultipleSomeMissingFiles.java
=> feat: Document using JBang on Windows, improve diagnosability of symbolic linking issues

src/main/scripts/jbang, src/main/scripts/jbang.ps1
The scripts will now detect if an install is missing
a required file and try to re-download.
=> fix: Make startup scripts a little more foolproof

build.gradle
Sometimes tests fail on my machine, because spotless checks the JUnit test report file. There is no need to check this file
=> chore: Ignore build reports and test results in spotless

docs/modules/ROOT/pages/caching.adoc, docs/modules/ROOT/pages/dependencies.adoc, docs/modules/ROOT/pages/installation.adoc
Fixes #785
Add short documentation of the 3 undocumented environment variables JBANG_DIR, JBANG_REPO and JBANG_CACHE_DIR listed in #785
=> fix: Docs don't explain several JBANG_ env vars #785

src/main/java/dev/jbang/source/ResourceRef.java, src/test/java/dev/jbang/source/TestTrustedSources.java
When running something like:
jbang run https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/2.0.0.Final/quarkus-cli-2.0.0.Final-runner.jar
jbang would offer to trust https://repo1.maven.org which is too broad as
default.
Fixed this by adding pattern match for repo1.maven.org so it will suggest
closest Group and Artifact (i.e. https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/)
and have the fallback when url not recognized to just return the parent path.
i.e. https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/2.0.0.Final/
assuming repo1.maven.org was not covered.
Fixes #944
=> fix: better trust url for maven central and default to parent url

src/main/java/dev/jbang/Settings.java, src/test/java/dev/jbang/cli/TestSettings.java
<!-
Thanks for submitting your Pull Request!
Please delete this text, and add description of the topic solved by this PR.
To make releases as automated as possible we use conventional commits formats.
Thus commits and pull-requests titles should before merge follow the Conventional Commits spec.
Details in https://github.com/zeke/semantic-pull-requests
If in doubt then open the pull-request and we'll help you - Thank you!
-->
=> Honor maven.repo.local system property to align with maven and gradle behavior. JBANG_REPO env variable will win if both present.

docs/modules/ROOT/pages/templates.adoc, src/main/java/dev/jbang/cli/Init.java, src/test/java/dev/jbang/cli/TestInit.java
adds initial support for properties in `init`
makes -Dkey=value available as `{properties.key}` and `{key}` to avoid overshadow but also to prevent overwriting jbang defined values such as `{baseName}`.
not fully sold both are needed ....wdyt ?
fixes #960
=> feat: properties for init templates

src/main/java/dev/jbang/cli/Init.java, src/test/java/dev/jbang/cli/TestInit.java
This allows you to have a scriptref in your init template
so you can do things like:
```
before_install:
-  curl -Ls https://sh.jbang.dev | bash -s - app setup
install:
- ~/.jbang/bin/jbang export mavenrepo --force -O target -Dgroup=$GROUP -Dartifact=$ARTIFACT -Dversion=$VERSION {scriptref or 'main.java'}
- mkdir -p ~/.m2/repository
- cp -rv target/* ~/.m2/repository/
```
and then `jbang init -t jitpack@jbangdev whatever.file`
and then the templates know its `whatever.file` it should use as its target.
=> feat: be able to refer to scriptref in init templates

src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/Build.java, src/main/java/dev/jbang/cli/Run.java
Sorry Max, I forgot to move the `--catalog` option to the base class before creating the previous PR. The `build` command of course needs the same `--catalog` option (even if only for symmetry)
=> feat: `build` now has `--catalog` option too

src/main/java/dev/jbang/catalog/Alias.java, src/main/java/dev/jbang/catalog/Catalog.java, src/main/java/dev/jbang/catalog/CatalogUtil.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/Build.java, src/main/java/dev/jbang/cli/Run.java, src/main/java/dev/jbang/source/Source.java, src/test/java/dev/jbang/cli/TestAlias.java, src/test/java/dev/jbang/cli/TestAliasNearest.java, src/test/java/dev/jbang/cli/TestAliasNearestWithBaseRef.java, src/test/java/dev/jbang/cli/TestAliasWithBaseRef.java, src/test/java/dev/jbang/cli/TestCatalog.java, src/test/java/dev/jbang/cli/TestRun.java
Added the `java` (alt `java-version`) option we need for the MSFT support and also added `main` (alt `main-class`) because that was the only other option that might prevent code from running if not available (even if we most likely don't need it in this particular case).
=> feat: added `java` and `main` options to aliases

docs/modules/ROOT/pages/editing.adoc, itests/edit.feature, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/StrictParameterPreprocessor.java
fixes #993 by making open ide the default and add --no-open option to use it in a terminal context.
=> fix!: make edit open by default and add --no-open

.github/workflows/ci-build.yml, src/main/java/dev/jbang/net/JdkManager.java, src/main/java/dev/jbang/util/Util.java, src/main/scripts/jbang, src/main/scripts/jbang.cmd, src/main/scripts/jbang.ps1
initial attempt on using foojay.io to fetch jdks so we can get both old and new java versions via 
the same API.
Opens up for in future doing nice things like `//JAVA 18-ea` to get earlyaccess versions or even `//JAVA 11+(zulu)` to get 11 or higher using zulu.
For now made default for jbang to use termurin for 8, 11 and 17+, rest is adoptopenjdk.
For bash and windows download of default jdk this still uses adoptopenjdk api as it gives 
a url that returns the right binary.
=> fix: use disco/foojay instead of adoptopenjdk to get api that works with old and new jdk versions

CONTRIBUTING.adoc
Before this update, when making a change to `src/main/java/dev/jbang/net/JdkManager.java`, the script would re-add the file with the wrong path (`src/main/java/dev/jbang/ne-/JdkManager.java`) thus failing to properly commit.
```
❯ git commit -sam "fix: typo in temurin name"
Kotlin and/or Java found in staging, running:  ./gradlew -PdisableSpotlessCheck spotlessApply
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
BUILD SUCCESSFUL in 721ms
6 actionable tasks: 6 up-to-date
re-adding src/main/java/dev/jbang/ne-/JdkManager.java after formatting
warning: could not open directory …
```
=> docs: Update spotless pre-commit hook url

src/main/java/dev/jbang/cli/Init.java, src/test/java/dev/jbang/cli/TestAliasWithBaseRef.java, src/test/java/dev/jbang/cli/TestApp.java, src/test/java/dev/jbang/cli/TestExport.java, src/test/java/dev/jbang/cli/TestInit.java, src/test/java/dev/jbang/cli/TestRun.java
- removed unused variables/fields
- used static access of static methods when necessary
0 warnings in VS Code \o/
Signed-off-by: Fred Bricon <fbricon@gmail.com>
=> chore: eliminate warnings from code base

src/main/java/dev/jbang/source/ResourceRef.java
=> fix: kotlin edit now link to source rather than cache location

src/main/java/dev/jbang/util/Util.java
The link to the "Usage on Windows" section was outdated. This PR fixes this issue.
=> fix: Fixed link to "Usage on Windows"

itests/SankeyPlotTest.java, itests/SankeyPlotTestWithDeps.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/dependencies/Detector.java, src/main/java/dev/jbang/dependencies/ModularClassPath.java, src/main/java/dev/jbang/source/RunContext.java, src/main/java/dev/jbang/source/ScriptSource.java, src/test/java/dev/jbang/cli/TestInfo.java, src/test/java/dev/jbang/cli/TestRun.java, src/test/java/dev/jbang/dependencies/DependencyResolverTest.java
This now works:
```bash
jbang --java 17 --deps org.openjfx:javafx-graphics:17:mac --deps eu.hansolo.fx:charts:RELEASE https://github.com/HanSolo/charts/blob/master/src/test/java/eu/hansolo/fx/charts/SankeyPlotTest.java
```
Before `--deps` was added to the classpath but was not considered
part of the modular classpath thus the magic of detecting javafx dependencies
never took affect.
=> fix: --deps now gets special javafx treatments as //DEPS does

src/main/java/dev/jbang/cli/Init.java, src/main/resources/init-agent.java.qute, src/main/resources/init-cli.java.qute, src/main/resources/init-hello.java.qute, src/main/resources/init-hello.kt.qute, src/main/resources/init-qcli.java.qute, src/main/resources/initClass.java.qute, src/test/java/dev/jbang/cli/TestInit.java
add jbang init --deps to create files with initial dependecies set up.
--deps currently does zero validation/resolution - should we make it do that so it will fail early if depndency not reachable/resolvable ?
=> feat: jbang init --deps

docs/modules/ROOT/pages/installation.adoc
Hello
According to [sdkman][0]'s docs,
the correct command for updating a candidate is `upgrade`.
[0]: https://sdkman.io/usage#upgrade
=> docs: fixed command for updating jbang using sdkman

.github/workflows/publish-packages.yml, .github/workflows/tag-and-release.yml, jreleaser.yml
Update the JReleaser configuration ad GH workflows with latest changes required by v0.9
=> chore: Update release settings for JReleaser 0.9

.github/workflows/ci-build.yml, build.gradle, itests/itests.cmd, itests/itests.sh
basic enablement of code coverage with jacoco.
we are about 60%, not bad but should get integration test included too.
just need to find a way to get the jacoco agent locatipon and set JBANG_TOOL_OPTION and it should "just" work
﻿
=> chore: enable code coverage

src/main/scripts/jbang, src/main/scripts/jbang.cmd, src/main/scripts/jbang.ps1
Before the startup scripts would actually check if JAVA_HOME
points to a (seemingly) valid JDK, but the Java code would
not. The easiest solution was to just unset the JAVA_HOME
env var in the case it's invalid.
Fixes #1103
=> fix: Not using JAVA_HOME anymore if it's invalid

itests/sources.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/App.java, src/main/java/dev/jbang/cli/Build.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Export.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/cli/Run.java, src/main/java/dev/jbang/source/JarSource.java, src/main/java/dev/jbang/source/KotlinScriptSource.java, src/main/java/dev/jbang/source/RunContext.java, src/main/java/dev/jbang/source/ScriptSource.java, src/main/java/dev/jbang/source/Source.java, src/test/java/dev/jbang/cli/TestEdit.java, src/test/java/dev/jbang/cli/TestEditWithPackage.java, src/test/java/dev/jbang/cli/TestEditWithPom.java, src/test/java/dev/jbang/cli/TestExternalDeps.java, src/test/java/dev/jbang/cli/TestInfo.java, src/test/java/dev/jbang/cli/TestRun.java, src/test/java/dev/jbang/dependencies/TestGrape.java, src/test/java/dev/jbang/source/TestSameSourceInDifferentPaths.java, src/test/java/dev/jbang/source/TestScript.java, src/test/java/dev/jbang/source/TestSourcesMultipleSomeMissingFiles.java, src/test/java/dev/jbang/source/TestSourcesMutualDependency.java, src/test/java/dev/jbang/source/TestSourcesRecursivelyMultipleFiles.java
>    fix: Fixed NPE for `info` on sources with `//SOURCES` lines
>
>    Refactored API a bit because the `Source` classes were being asked to deal with context issues (like knowing about system properties) which are better handled at the level of `RunContext`.
>    
>    Fixes #1096
and
>    refactor: Removed use of static property resolver from `ScriptSource`
>    
>    Instead of relying on a static property resolver we now pass a resolver into the constructor of `ScriptSource`. For this the static factory methods for creating `Source` objects have been refactored as instance methods of `RunContext` (which knows about properties).
=> fix: Fixed NPE for `info` on sources with `//SOURCES` lines

.github/workflows/ci-build.yml, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/source/ResourceRef.java, src/main/java/dev/jbang/source/ScriptSource.java, src/test/java/dev/jbang/cli/TestRun.java
Before it would just assume that the `main()` method was located
in a class with the same name as the Java source file, but that's
not always the case. For example, when reading from stdin it's
hard to detect the right class and even more so when dealing with
non-public classes (non-public classes can still have `main()`
methods!)
Fixes #1099
=> fix: Improved `main()` method lookup

src/main/scripts/jbang
Fixes #642
Can someone with a Mac test this?
=> fix: JBang now correctly detects "fake" JDK on MacOS

itests/dependencies.feature, itests/test_suite.sh, src/main/java/dev/jbang/dependencies/DependencyCache.java, src/main/java/dev/jbang/dependencies/DependencyResolver.java, src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/dependencies/ModularClassPath.java, src/main/java/dev/jbang/source/JarSource.java, src/main/java/dev/jbang/source/RunContext.java, src/main/java/dev/jbang/source/ScriptSource.java, src/main/java/dev/jbang/source/Source.java, src/test/java/dev/jbang/dependencies/TestArtifactInfo.java
Includes these two important commits:
> **refactor: Improved dependency handling …**
>
> `Source` dependency handling has been improved so that regardless of the sources or command line options like `--deps` we'll only do a single call to the dependency resolver.
and
> **refactor: Aether now resolves all deps in a single go …**
>
> This fixes any problems with duplicate and conflicting dependencies because we used to handle each dependency separately. The downside, for now, is that we can't log the dependency resolution to the output for the user to see what's happening.
=> Better deps handling

src/main/scripts/jbang
One character fix for inverted if-condition.
Fixes #642
=> fix: check for `javac` should now work on Mac

src/main/java/dev/jbang/dependencies/DependencyResolver.java, src/main/java/dev/jbang/source/ResourceRef.java, src/main/java/dev/jbang/source/ResourceResolver.java, src/main/java/dev/jbang/source/RunContext.java, src/main/java/dev/jbang/source/resolvers/ClasspathResourceResolver.java, src/main/java/dev/jbang/source/resolvers/CombinedResourceResolver.java, src/main/java/dev/jbang/source/resolvers/FileResourceResolver.java, src/main/java/dev/jbang/source/resolvers/GavResourceResolver.java, src/main/java/dev/jbang/source/resolvers/RemoteResourceResolver.java, src/main/java/dev/jbang/source/resolvers/RenamingScriptResourceResolver.java, src/main/java/dev/jbang/source/resolvers/StdinScriptResourceResolver.java, src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/cli/TestRun.java, src/test/java/dev/jbang/util/TestTrustedSources.java
This is a continuation of the work on #1111 
The `--deps` and `--repos` now also work when dealing with GAVs.
There's also a pretty decent refactor included that splits out the resolving of `ResourceRef`s out into a separate `ResourceResolver` that uses a plugin system where each type of resolving (remote, from classpath, from stdin, etc) is done by its own class. There's a bit more code now but it's much clearer who's responsible for what.
=> Better deps continued

itests/catalog.feature, src/main/java/dev/jbang/catalog/Catalog.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/Template.java, src/main/java/dev/jbang/source/ResourceRef.java, src/main/java/dev/jbang/source/resolvers/RemoteResourceResolver.java, src/main/java/dev/jbang/util/Util.java
Running `alias list` or `template list` would not show full catalog
names when appropriate. This now works again. Also added a minor fix
where implicit catalogs won't get added twice if different names point
to the same catalog, eg: `jbangdev` and `jbangdev/jbang-catalog` are
the same catalog but would be added twice with those different names.
We now first try simplify the name before using it. So in the above
case `jbangdev/jbang-catalog` would become `jbangdev`.
Fixes #1089
=> fix: Fixed regression not showing catalog names

src/main/java/dev/jbang/cli/App.java, src/main/java/dev/jbang/cli/Wrapper.java, src/main/java/dev/jbang/util/Util.java
Normally when you run `jbang app install jbang` a fresh copy of the
latest version of Jbang will be downloaded, unpacked and installed.
But this patch allows the currently running jbang to be used as the
source for the files to install. This is done by supplying the
option `--offline` to prevent Jbang from downloading the latest version.
=> feat: Allow jbang to install itself

src/main/java/dev/jbang/cli/CommaSeparatedConverter.java, src/main/java/dev/jbang/cli/DependencyInfoMixin.java, src/main/java/dev/jbang/cli/Init.java, src/test/java/dev/jbang/cli/TestInfo.java, src/test/java/dev/jbang/cli/TestInit.java, src/test/java/dev/jbang/cli/TestRun.java
Allow several dependencies to be provided with `--deps` using comma separator. For example:
`--deps info.picocli:picocli:4.5.0,commons-io:commons-io:2.8.0`
=> fix: Allow --deps to specify multiple dependencies (#815)

itests/quote.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/BaseCommand.java, src/main/java/dev/jbang/cli/Export.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/cli/JBang.java, src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/source/ScriptSource.java, src/main/java/dev/jbang/source/Source.java, src/main/resources/pom.qute.xml, src/test/java/dev/jbang/cli/TestExport.java, src/test/java/dev/jbang/cli/TestInfo.java, src/test/java/dev/jbang/cli/TestRun.java, src/test/java/dev/jbang/source/TestScript.java
This adds support for a `//GAV group:artifact[:version]` to be added
to source files. This information is then used when generating POM
files, like when doing a build or when running `export mavenrepo`.
Fixes #1132
=> feat: Allow for a //GAV line in source files

src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Jdk.java, src/main/java/dev/jbang/util/Util.java, src/main/scripts/jbang
Running inside a Bash shell on Windows we got a couple of regressions:
- the bash script needs to be able to perform the Windows update procedure. (The issue is that when using Cygwin/Git Bash on Windows and trying to update Jbang will download the new version but the switch to the new version won't actually be performed.)
-  `jbang edit` using wrong paths on Windows (All paths that get printed out to the output need to be passed through `Util.pathToString()`)
=> fix: Some regressions for Windows

src/main/java/dev/jbang/net/KotlinManager.java
Fix #1148 Update DEFAULT_KOTLIN_VERSION to 1.6.10
=> fix: update default Kotlin version to 1.6.10

src/main/java/dev/jbang/util/Util.java
This bug  will stop Kotlin source to compile, and it was introduce by me to test kts file during Groovy PR.  Sorry about this fault.
=> fix: rename ".kts" ot ".kt"

itests/dependencies.feature, itests/test_suite.sh, src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/dependencies/MavenRepo.java
JBang now for known shrinkwrap resolution exception prints
error message that contains custom repo list + cause chain on ouptut
without having to use `--verbose` to see it.
Fixes #1123
=> fix: Provide context about depedendency resolution error.

src/main/java/dev/jbang/cli/Info.java, src/test/java/dev/jbang/cli/TestInfo.java
=> fix: stop tools info .jsh from failing

docs/modules/ROOT/pages/exporting.adoc, itests/export.feature, src/main/java/dev/jbang/cli/Export.java, src/main/java/dev/jbang/cli/ExportMixin.java, src/test/java/dev/jbang/cli/TestExport.java
- Option to put the lib folder into the final jar
=> fix: Renaming libs to lib when calling export portable

src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/test/java/dev/jbang/dependencies/DependencyResolverTest.java
ShrinkWrap does not have direct support for multiple pom files to use
for resolving versions for dependencies without version, i.e. called
`<dependencyManagement>` in Maven, platforms in Gradle.
To fix it we now generate a temporary pom.xml that has nothing but a
<dependencyManagement> section containg the list of managed pom dependencies.
This has the following consequences:
- we need to write a temporary file as ShrinkWrap does not allow passing a string directly.
- we avoid loading a bom pom as a pom which will activate parent poms features like adding repositories that generated warnings. Now this just don't happen.
- means that @pom references now can come in any order (before we required it to be the first)
- consequence of that is there in effect will be to `//DEPS` lists; one is …
=> feat: support multiple bom poms

src/jreleaser/distributions/jbang/docker/README.md.tpl
GH-Action requires the `v`. Fixes the readme for the action repository.
=> Use `tagName` instead of `projectVersion`

src/main/java/dev/jbang/cli/Config.java
=> fix: config set/remove should tell what file it edits

src/main/java/dev/jbang/cli/App.java
=> fix: failing `app setup` on Windows

docs/modules/ROOT/pages/intro.adoc
Add missing backticks for `.kt` and `.groovy`
=> docs: Formatting fixes

src/main/scripts/jbang, src/main/scripts/jbang.ps1
The startup scripts were not taking into account the `distro` argument
for the different java versions
Fixes #1195
=> fix: Fixed JDK download URLs for startup scripts

src/main/java/dev/jbang/cli/App.java
Trying to fix #1192 by just do a build of ref.
=> fix: app install builds before installing scripts

docs/modules/cli/pages/jbang-template-add.adoc, src/main/java/dev/jbang/catalog/Catalog.java, src/main/java/dev/jbang/catalog/CatalogUtil.java, src/main/java/dev/jbang/catalog/Template.java, src/main/java/dev/jbang/catalog/TemplateProperty.java, src/main/java/dev/jbang/cli/Catalog.java, src/main/java/dev/jbang/cli/Template.java, src/main/java/dev/jbang/cli/TemplatePropertyConverter.java, src/test/java/dev/jbang/cli/TemplatePropertyConverterTest.java, src/test/java/dev/jbang/cli/TestTemplate.java
- Property can have description and default value
- Adding multiple property at the same time with a specific format
- Listing templates returns the list of the template properties too
Associated issue: https://github.com/jbangdev/jbang/issues/1203
=> feat: Catalog templates with property list

docs/modules/ROOT/pages/installation.adoc
"Manual Install" and "Gradle Plugin" should not be under "Maven Plugin".
=> fix: headline levels

src/main/java/dev/jbang/util/Util.java
We now compare "real paths" to determine if Jbang is managed or not
Fixes #1193
=> fix: fixed check for using managed jbang

src/main/scripts/jbang
For Cygwin all kinds of path mangling is necessary, so reverting back
to calling `jbang.cmd` when we detect Cygwin. This does mean that
Jbang will fail to give proper usage instructions in certain cases
when running with Cygwin.
Fixes #1223
=> fix: Fixed Jbang failing to run correctly with Cygwin

docs/modules/ROOT/pages/usage.adoc, src/main/java/dev/jbang/net/JdkManager.java, src/main/java/dev/jbang/util/Util.java, src/main/scripts/jbang, src/main/scripts/jbang.ps1
=> Allow user to set JDK release

docs/modules/ROOT/pages/organizing.adoc, itests/funcs.jsh, itests/jsh.feature, itests/main.jsh, src/main/java/dev/jbang/cli/Run.java, src/test/java/dev/jbang/cli/TestRun.java
=> fix: `//SOURCES` now work in .jsh files too

docs/modules/ROOT/pages/configuration.adoc, itests/wrapper.feature, src/main/resources/jbang.properties, src/test/java/dev/jbang/cli/TestConfig.java
Fixes #1233
Simple fix. It was only because the wrong config property name was used in the default config file.
=> fix: fixes erroneous config property

docs/modules/ROOT/pages/usage.adoc, itests/bar/Bar.java, itests/foo.java, itests/jsh.feature, itests/run-nix.feature, itests/run.feature, src/main/java/dev/jbang/Main.java, src/main/java/dev/jbang/catalog/Alias.java, src/main/java/dev/jbang/catalog/Catalog.java, src/main/java/dev/jbang/catalog/CatalogUtil.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/BaseScriptCommand.java, src/main/java/dev/jbang/cli/Build.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/cli/Init.java, src/main/java/dev/jbang/cli/Run.java, src/main/java/dev/jbang/source/MarkdownScriptSource.java, src/main/java/dev/jbang/source/ResourceRef.java, src/main/java/dev/jbang/source/ResourceResolver.java, src/main/java/dev/jbang/source/RunContext.java, src/main/java/dev/jbang/source/ScriptSource.java, src/main/java/dev/jbang/source/resolvers/LiteralScriptResourceResolver.java, src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/cli/TestAliasNearest.java, src/test/java/dev/jbang/cli/TestAliasNearestWithBaseRef.java
The `--code` (or `-c`) option either takes a String argument (using `=`)
that will be taken as a literal script or it can appear without argument
in which case the `scriptOrFile` argument will be assumed to contain a
literal script. In both cases the literal script will be executed in
the same way as if the code was passed on the stdin (that is, the code
will be assumed to be Jshell code unless it obviously is plain Java).
Also allows the `--interactive` option to be used without any script
reference at all.
The shortcut `-i` was added for `--interactive`.
Fixes #1242
=> feat: Added `--code` option for running literal scripts

src/main/java/dev/jbang/cli/Run.java
lets you do:
```
for i in {1..50}; do echo $((1 + $RANDOM % 80)); done | jbang -c 'lines().forEach(s->System.out.println("x".repeat(Integer.valueOf(s))))'
```
=> feat: add lines() to access stdin per line

src/main/java/dev/jbang/cli/Run.java
=> fix: showing proper error when using `-c` without code

src/main/java/dev/jbang/util/Util.java, src/main/scripts/jbang
Attempt to fix https://github.com/jbangdev/jbang/discussions/1265 that notices that on M1 that identifies as arm64 won't auto download java.
=> fix: support M1 initial macs java downloads

docs/modules/ROOT/pages/dependencies.adoc
Make explicit why groovy is needed.
Use java quotes in the line:
`@GrabResolver(name="acme", root="https://maven.acme.local/maven")`
The example does still not compile:
```
classpath_example.java:15: error: GrabResolver is not a repeatable annotation type
@GrabResolver(name="acme", root="https://maven.acme.local/maven")
^
1 error
[jbang] [ERROR] Error during compile
[jbang] Run with --verbose for more details
```
But it is better.
=> docs: Make explicit why groovy is needed

src/main/java/dev/jbang/Configuration.java, src/main/java/dev/jbang/cli/BaseCommand.java, src/main/java/dev/jbang/cli/Config.java, src/test/java/dev/jbang/TestConfiguration.java
The `Configuration` wasn't storing the originating `ResourceRef` in the
case of single file configurations (which is what `--global` is).
To fix this the code has been made more similar to `Catalog`.
Fixes #1275
=> fix: no longer throws NPE for config list

itests/jsh.feature, src/main/java/dev/jbang/source/generators/JshCmdGenerator.java
Runtime options were being passed literally to Jshell which doesn't
work. All options for the JVM need to pe prefixed with `-J`.
Also the ordering of `-s` sources needed to be reversed.
=> fix: some minor Jshell fixes

src/main/java/dev/jbang/cli/Edit.java
Fixes #1068
Was a good beginner issue but it was already open for too long :-)
=> fix: properly quote edit command on Windows

build.gradle, docs/modules/ROOT/pages/alias_catalogs.adoc, src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java, src/test/java/dev/jbang/TestImplicitAlias.java
some times creating a root jbang-catalog repo can be problematic or the base github user/org is not really related so instead of `jbang cli@awesomefwk` it becomes `jbang cli@l33t1974/awesomefwk`
For a while I had the idea jbang alias should support allowing `jbang main@awesome.fwk` where `awesome.fwk` is treated as https://awesome.fwk instead of looked up in github/gitlab names.
It is only a draft for now but if you build this (with -x test as the test is broken for now) you can do:
`jbang main@jbang.dev` because I created https://jbang.dev/jbang-catalog.json
similar `jbang tree@jbang.dev` works.
imagine, `jbang quarkus@redhat.com` as opposed to `jbang quarkus@RedHatOfficial`  - as an example.
wdyt ?
btw. this also enables `jbang yourscript@https://whatever.path/sdf/sf/jbang-catalog.json` …
=> feat: enable jbang tree@jbang.dev and jbang tree@https:/jbang.dev

src/main/java/dev/jbang/catalog/CatalogRef.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/cli/Init.java, src/main/java/dev/jbang/source/RefTarget.java, src/main/java/dev/jbang/source/ResourceRef.java, src/main/java/dev/jbang/source/ResourceResolver.java, src/main/java/dev/jbang/source/RunContext.java, src/main/java/dev/jbang/source/Source.java, src/main/java/dev/jbang/source/SourceSet.java, src/main/java/dev/jbang/source/resolvers/AliasResourceResolver.java, src/main/java/dev/jbang/source/resolvers/CombinedResourceResolver.java, src/main/java/dev/jbang/source/resolvers/RemoteResourceResolver.java, src/main/java/dev/jbang/source/resolvers/SiblingResourceResolver.java, src/main/java/dev/jbang/source/sources/GroovySource.java, src/main/java/dev/jbang/source/sources/JavaSource.java, src/main/java/dev/jbang/source/sources/KotlinSource.java, src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/cli/TestRun.java
You can now use aliases within `//SOURCES` tags.
NB: Only qualified aliases are supported! So the alias needs to have a `@`.
=> feat: allow aliases for `//SOURCES`

src/main/java/dev/jbang/source/Source.java, src/main/java/dev/jbang/source/builders/BaseBuilder.java, src/main/java/dev/jbang/spi/IntegrationInput.java, src/main/java/dev/jbang/spi/IntegrationManager.java, src/main/java/dev/jbang/spi/IntegrationResult.java
=> feat: enable integrations to run externally

src/main/java/dev/jbang/source/RunContext.java, src/test/java/dev/jbang/cli/TestRun.java
=> fix: give proper error when `-s` file is missing

src/main/java/dev/jbang/source/Jar.java, src/main/java/dev/jbang/source/RunContext.java, src/main/java/dev/jbang/source/SourceSet.java, src/main/java/dev/jbang/source/builders/BaseBuilder.java, src/test/java/dev/jbang/cli/TestRun.java
If the code had `//REPOS` tags and it would get run with `--deps`
on the command line then those deps would not get resolved against
the repostories mentioned in the `//REPOS` tags if no build was being
performed.
Fixes #1292
=> fix: fixed problem `--deps` and `//REPOS`

src/main/java/dev/jbang/util/ConsoleInput.java, src/main/java/dev/jbang/util/ConsoleInputReadTask.java, src/main/java/dev/jbang/util/Util.java
This means that the GUI that was introduced a while back to be able to
ask the user for feedback when the stdin was redirected will no longer
be used on Linux and Mac, but only on Windows.
The main advantage of this is that zero-install using `curl` will
work when no GUI is available (eg when using containers).
=> feat: fall back to TTY when asking for input on Linux/Mac

src/main/scripts/jbang, src/main/scripts/jbang.ps1
We're not doing a "hidden install" anymore, but (inefficiently)
downloading Jbang to a temporary location and cleaning it up after
each invocation.
Fixes #1218
=> feat: "zero" install now lives up to its name

src/jreleaser/distributions/jbang/docker/Dockerfile.tpl, src/jreleaser/distributions/jbang/docker/entrypoint
Use jbang full path to bypass 'act' issue with PATH environment variable
=> fix: Run locally with 'act' fails (jbangdev/jbang-action#28)

docs/modules/ROOT/pages/usage.adoc, src/main/java/dev/jbang/cli/Edit.java, src/test/java/dev/jbang/cli/TestEdit.java, src/test/java/dev/jbang/cli/TestEditWithPackage.java, src/test/java/dev/jbang/cli/TestEditWithPom.java
Just a few changes to make it easier to
update edit. 
should not break/change things besides the cleanup removing what seems to me like redundant calls and introduce a generic watch method with a callback.
=> chore: cleaner edit code for easier refactor/improve

src/main/java/dev/jbang/cli/StrictParameterPreprocessor.java
=> chore: fix typo in StrictParameterPreprocessor.java

docs/modules/ROOT/pages/alias_catalogs.adoc
fix: some errors in alias documentation page:
1. Incorrect description for https alias usage
2. Missing local path information
3. Missing quote
=> fix: some errors in alias documentation page

misc/proxy/README.md, misc/proxy/docker-compose.yml
This allows you to easily start up a proxy and a container with a shell
and JBang pre-installed that is only allowed to connect to the proxy.
Includes a README with some instructions.
See #447
=> test: added docker compose file for testing proxy

src/test/java/dev/jbang/cli/TestRun.java
PR had passed the tests back in the time but the code had changed in the mean time and although it applied cleanly it caused compile errors. See #1271
=> fix: Fixed problem with merging old PR #1271

src/test/java/dev/jbang/cli/TestRun.java
Because `java.nio.file.FileSystems#newFileSystem(java.nio.file.Path, java.util.Map<java.lang.String,?>)` was introduced in JDK 13+, using only `null` without casting leads to
compilation errors when building in JDK 17 for example
=> chore: add explicit cast

src/main/java/dev/jbang/spi/IntegrationManager.java
if you use --class-path xyz.jar no GVA is present which currently makes integration calls fail.
This fixes it so NPE does not occur; but long term we should find a way to include classpath for integration calls.
=> fix: ignore dependencies without GVA for integration

src/main/java/dev/jbang/source/generators/BaseCmdGenerator.java
Now don't use @files for jshell as jshell has no such support.
=> fix: do not use @file with jshell. Fixes #1349

src/main/java/dev/jbang/cli/DependencyInfoMixin.java, src/main/java/dev/jbang/dependencies/DependencyUtil.java
`--verbose` now print list of active maven repositories used for resolution.
`--deps` now work as comma separated list
spring-snapshot,spring-milestone,s01sonatype-snapshots and sontatype-snapshots now
available as short for maven repositories.
=> feat: improve maven repo shorthand and logging

src/main/java/dev/jbang/Settings.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Export.java, src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/source/builders/BaseBuilder.java, src/main/java/dev/jbang/source/generators/BaseCmdGenerator.java, src/main/java/dev/jbang/source/generators/JshCmdGenerator.java, src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/cli/TestEdit.java, src/test/java/dev/jbang/cli/TestEditWithPackage.java, src/test/java/dev/jbang/cli/TestEditWithPom.java, src/test/java/dev/jbang/cli/TestExport.java
Moves away from java.io.File to use Path and Masters
simplifies  and remove a bunch of unnecessary toPath transforms we have
=> fix: move away from java.io.File to Path/Files

src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/ExportMixin.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/source/Source.java
Add comma separation handling to --sources + fix minor issue where "@Grab(" in jbang gets picked up when trying to build jbang with jbang.
=> fix: --sources now handle comma separated input

src/main/java/dev/jbang/catalog/CatalogUtil.java, src/test/java/dev/jbang/cli/TestAlias.java
Aliases were not correctly added in those cases where a target catalog
file was not explicitely provided.
Fixes #1367
=> fix: aliases now correctly added

docs/modules/ROOT/pages/configuration.adoc
=> chore: fix typo in configuration.adoc

src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/Export.java, src/test/java/dev/jbang/cli/TestAlias.java, src/test/java/dev/jbang/cli/TestEdit.java, src/test/java/dev/jbang/cli/TestExport.java, src/test/java/dev/jbang/cli/TestRun.java
Fixes NPE that would happen if you leave out a required script
parameter for commands like export and alias add.
Fixes #1375
=> fix: fixed certain commands not validating input correctly

src/test/java/dev/jbang/cli/TestRun.java
Fixes #1377 
Add a test to prevent `ConcurrentModificationException` when `--repos`. This test was failing with `0.94.0` and is now green on top of `main`.
=> test: Add test with --fresh and --repos

src/main/scripts/jbang
=> fix: properly detect existing JDK on Macs

src/main/java/dev/jbang/source/builders/BaseBuilder.java, src/main/java/dev/jbang/util/Util.java
We no longer assume the compiler executables will always be .exe when
running on Windows. In fact in the latest Graal versions the
`native-image` executable is a .cmd file.
Fixes #1394
=> fix: looking for compiler executables on Windows

src/main/java/dev/jbang/cli/Wrapper.java
We didn't copy this before because having just `jbang.cmd` was thought
to be enough for Windows. But some time ago we actually removed all
installation code from the batch file and delegate any installation
requirements to the .ps1 file. So the wrapper installation was missing
a file on Windows.
Fixes #1386
=> fix: `wrapper install` now also copies jbang.ps1

docs/modules/ROOT/pages/running.adoc
This PR just changes `COMPILER_OPTS` to `JAVAC_OPTIONS`, as shown by the example.
=> fix: Small typo when referring to `JAVAC_OPTIONS`

src/main/java/dev/jbang/cli/Export.java, src/main/java/dev/jbang/source/builders/BaseBuilder.java
We used to add absolute paths for all dependencies to the MANIFEST.MF
file inside the JAR files Jbang creates. But this is actually not
according to spec, paths may only be relative, but it often just
worked fine. Except that Graal's `native-image` transpiler doesn't
lke that at all. So now we don't generate those `Class-Path` entries
anymore by default, only when using `export local` and `export portable`
will the `Class-Path` be set.
Fixes #1396
=> fix: don't add `Class-Path` by default to JARs

src/main/java/dev/jbang/cli/Info.java, src/test/java/dev/jbang/cli/TestInfo.java
Fixes #1425
Tests didn't check for this, now they do.
=> fix: info tools again generates info for nested sources

src/main/resources/settings.qute.json
Hide .project/.classpath from virtual project in VS Code (when running `jbang edit`), as they're unnecessary noise
=> feat: Hide .project/.classpath from virtual project in VS Code

src/main/java/dev/jbang/net/KotlinManager.java
=> fix: change kotlinc's extension to .bat on Windows

src/main/java/dev/jbang/net/JdkManager.java, src/main/scripts/jbang, src/main/scripts/jbang.ps1
update to use v3 so we get GA or early access versions if no GA available.
=> fix: update to disco v3 endpoints

itests/sources/yang.java, itests/sources/ying.java, src/main/java/dev/jbang/cli/Info.java, src/test/java/dev/jbang/cli/TestInfo.java
Fixes #1464, but i'm not sure this is the right fix.
uses Project to know if already processed sources, but feels wrong that only Info.java has to change.
=> fix: avoid infinite recursion with **.java

docs/modules/ROOT/pages/running.adoc
=> docs: fix typo in running.adoc

.github/PULL_REQUEST_TEMPLATE.md
The link in the template are outdated
=> docs: update links to the Conventional Commits spec

docs/modules/ROOT/pages/javaversions.adoc
Update the documentation to mention what is discussed in https://github.com/jbangdev/jbang/issues/1476#issuecomment-1271208199
It is possible to use `jdk install` and provide the path of the installed JDK.
This can also be combined with SDKMAN!
=> docs: Explain how you can install an existing jdk

itests/helloworld.java, src/main/java/dev/jbang/source/buildsteps/NativeBuildStep.java, src/test/java/dev/jbang/source/TestBuilder.java
This is a fix for PR #1494 which implemented all the necessary API and UI elements.... but didn't actually pass the options to the native image builder :roll_eyes:
=> fix: now actually passing native options to `nativeimage`

src/main/scripts/jbang, src/main/scripts/jbang.ps1
allows to do:
`curl -Ls https://sh.jbang.dev | JBANG_DOWNLOAD_VERSION=0.99.2 bash -s - app setup`
Similar for Windows but haven't tested it - thus marking this draft for now.
=> feat: honor JBANG_DOWNLOAD_VERSION in bootstrap setup

src/main/java/dev/jbang/net/JdkManager.java
After installing jbang through sdkman ==> `sdk install jbang`. I wanted jbang to use an already installed jdk version from sdk, so I ran the command `jbang jdk install 17 $(sdk home java 17.0.5-tem)`
I got the following error :
> [jbang] java.nio.file.NoSuchFileException: /home/john/.jbang/cache/jdks/17
[jbang] Creation of symbolic link failed.
[jbang] Now try creating a hard link instead of symbolic.
[jbang] Creation of hard link failed. Script must be on the same drive as $JBANG_CACHE_DIR (typically under $HOME) for hardlink creation to work. Or call the command with admin rights.
[jbang] [ERROR] java.nio.file.NoSuchFileException: /home/john/.jbang/cache/jdks/17 -> /home/john/.sdkman/candidates/java/17.0.5-tem
[jbang] Run with --verbose for more details 
Jbang is trying to create a …
=> fix: ensure cache jdks directory exists before creating link

itests/helloworld.kt, src/main/java/dev/jbang/source/buildsteps/CompileBuildStep.java, src/main/java/dev/jbang/source/sources/JavaSource.java, src/main/java/dev/jbang/source/sources/KotlinSource.java, src/test/java/dev/jbang/source/TestBuilder.java, src/test/java/dev/jbang/source/TestSource.java
Only add -g for javac invocations so kotlin scripts can be compiled.
fixes #1512
=> only add -g for javac invocations.

src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/cli/TestRun.java
Twitter blocked no-javascript access but mastodon does not have this issue.
Thus this PR enables you to do this: 
`jbang https://fosstodon.org/@jbangdev/109367735752497165`
it will match any URL that matches `https://.*/@(\w+)/([0-9]+)` which afaics are fairly specific to mastodon style urls.
=> feat: mastodon url support

src/main/scripts/jbang.cmd
Tested the change by:
1. Downloaded 101.0 zip on Windows Sandbox
2. Extracted the zip
3. Modified jbang.cmd:
Before:
```
echo powershell -NoProfile -ExecutionPolicy Bypass -NonInteractive -Command "%~dp0jbang.ps1 jdk install %JBANG_DEFAULT_JAVA_VERSION%"
```
After:
```
powershell -NoProfile -ExecutionPolicy Bypass -NonInteractive -Command "%~dp0jbang.ps1 jdk install %JBANG_DEFAULT_JAVA_VERSION%"
```
4. Run jbang
=> fix: Fixes the "The system cannot find the path specified" (#1520)

src/main/java/dev/jbang/source/Source.java, src/main/java/dev/jbang/spi/IntegrationManager.java
- properly passing tags to the integrations again
- fixed that the integrations were running externally in too many cases where the current JVM was matching but wasn't used.
- passing properties to external integrations
=> fix: make integrations work again

src/main/java/dev/jbang/util/Util.java
Adds support for basic-auth when loading a script.
Usage:
export JBANG_BASIC_AUTH_USERNAME=<username>
export JBANG_BASIC_AUTH_PASSWORD=<password>
jbang https://<company domain>/.....
=> feat: support basic-auth for loading scripts

docs/modules/ROOT/pages/dependencies.adoc, src/main/java/dev/jbang/cli/DependencyInfoMixin.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/dependencies/ArtifactResolver.java, src/main/java/dev/jbang/dependencies/DependencyResolver.java, src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/dependencies/DependencyResolverTest.java, src/test/java/dev/jbang/dependencies/TestArtifactInfo.java
adding option to have jbang download sources for dependencies.
approach is a bit a naive and will only work if all //DEPS resolves properly but simply
takes the resolved set and then one by one try resolve matching sources classifier.
=> feat: adding auto download for sources via edit and JBANG_DOWNLOAD_SOURCES=true

src/main/java/dev/jbang/cli/Alias.java
Bug fix
-Build was successful
-native command would work now
https://github.com/jbangdev/jbang/issues/1531
=> issue #1531

src/main/java/dev/jbang/dependencies/DependencyCache.java, src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/main/java/dev/jbang/source/Project.java
When running a previously built app jbang would sometimes resolve artifacts twice
=> Fix double resolve

src/main/java/dev/jbang/cli/App.java
When the user runs `app setup` when, according to Jbang, the environment was already set up correctly a message will be shown that the user can add the `--force` flag to perform the setup anyway.
See #1524
=> chore: `app setup` now tells user about `--force`

src/main/scripts/jbang
Using `bash -x jbang` will now work correctly.
See #1540
=> feat: improved Linux/Mac startup script

src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/Export.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/source/AppBuilder.java, src/main/java/dev/jbang/source/ProjectBuilder.java, src/test/java/dev/jbang/cli/TestInfo.java
We added a way to skip importing metadata into a Project if a JAR was available locally, but that was still causing problems in certain situations. For example if you would compile with Java 19 and then uninstall Java 19 leaving an earlier version, let's say Java 11, jbang would try to download Java 19 just to run the code, even though nothing in the source indicated that was necessary. In that case it's much more convenient to simply recompile the code with Java 11. The solution now is to not import the metadata into the Project anymore, but to make it an explicit action of reading the information and let the code that does the reading decide what to do with it.
=> fix: we don't blindly import JAR metadata anymore

src/main/java/dev/jbang/source/sources/GroovySource.java
The `JAVA_HOME` wasn't being set up correctly. This was a regression.
Fixes #1554
=> fix: Groovy compiler now runs correctly

src/main/java/dev/jbang/cli/App.java
The jbang update process now set cache-evict to 0 before trying to download any new versions.
=> fix: not using cache for jbang update anymore

src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/util/UnpackUtil.java, src/test/java/dev/jbang/cli/TestInfo.java
=> fix: `info tools` now downloads JDKs again

docs/modules/ROOT/pages/configuration.adoc, src/main/java/dev/jbang/cli/FormatMixin.java, src/main/java/dev/jbang/cli/JBang.java, src/main/java/dev/jbang/cli/JdkProvidersMixin.java, src/main/java/dev/jbang/net/JdkManager.java, src/main/resources/jbang.properties, src/test/java/dev/jbang/cli/TestAlias.java, src/test/java/dev/jbang/cli/TestCatalog.java, src/test/java/dev/jbang/cli/TestConfig.java, src/test/java/dev/jbang/cli/TestInfo.java, src/test/java/dev/jbang/cli/TestRun.java, src/test/java/dev/jbang/cli/TestTemplate.java
Some default values were not settable by config, an oversight.
Also added the possibility to globally set default values for all commands that support the same option.
Fixes #1576
=> fix: all default values can be set by config

src/main/java/dev/jbang/cli/JdkProvidersMixin.java, src/main/java/dev/jbang/source/resolvers/ClasspathResourceResolver.java
The underlying issue was that classpath resources were not being properly duplicated to the file system, resulting in them never being updated. This meant that newer config option were left empty.
=> fix: Fixed NPE dealing with jdk providers

src/main/java/dev/jbang/cli/Export.java, src/main/java/dev/jbang/source/AppBuilder.java, src/main/java/dev/jbang/source/buildsteps/JarBuildStep.java, src/main/java/dev/jbang/util/JarUtil.java, src/test/java/dev/jbang/cli/TestRun.java
We had to switch back to using the external `jar` command to create or update JARs because there doesn't seem to be an easy way to set the main class for Java modules without it.
=> fix: make sure we set main class in module jars

.github/workflows/ci-build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/install-tests.yml, .github/workflows/publish-packages.yml, .github/workflows/tag-and-release.yml, jreleaser.yml
Update JReleaser configuration to 1.5.1
Update GH workflows with latest versions of several actions due to phase out of node 12 (see warnings on workflow executions).
=> refactor: update release configuration

src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/JBang.java, src/main/java/dev/jbang/cli/RunMixin.java, src/main/resources/jbang.properties
The way config values were being turned into a resource bundle te be used in PicoCli's default values was conflicting with PicoCli's resource string for usage/help. We now make sure our names don't conflict with those that PicoCli uses.
Fixes #1614
=> fix: no longer throws exception for certain config values

build.gradle, src/main/java/dev/jbang/catalog/Alias.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/JBang.java, src/main/java/dev/jbang/source/Project.java, src/main/java/dev/jbang/source/ProjectBuilder.java, src/main/java/dev/jbang/source/Source.java, src/main/java/dev/jbang/source/buildsteps/CompileBuildStep.java, src/main/java/dev/jbang/source/generators/JarCmdGenerator.java, src/main/java/dev/jbang/source/generators/JshCmdGenerator.java, src/main/java/dev/jbang/source/generators/NativeCmdGenerator.java, src/test/java/dev/jbang/cli/TestRun.java, src/test/java/dev/jbang/source/TestBuilder.java
Why:
* --enable-preview is a common flag to enable preview features in Java 9 and up
but is hard to use with jbang as it is not passed on to the java,javac
and jshell command when running a script.
* workaround thus far been to pass -C=--enable-preview and -R=--enable-preview
but that does not work for jshell
This change addreses the need by:
* introducing `--enable-preview` flag to jbang which will pass it on to
java, javac and jshell as appropriate
* `//PREVIEW` in source files is possible
* aliases can specify enable preview too.
Fixes #1622
=> feat: add support for --enable-preview

itests/karate.java, itests/nakedmain.feature, itests/nakedmain/classinstance.java, itests/nakedmain/noclass.java, itests/nakedmain/noclasswithargs.java, src/main/java/dev/jbang/source/buildsteps/CompileBuildStep.java, src/main/java/dev/jbang/util/Util.java, src/main/scripts/choco/jbang.nuspec, src/test/java/dev/jbang/cli/TestJdk.java, src/test/java/dev/jbang/util/TestUtil.java
initial support for jep 445 - it might be too optimistic but at least it works in last nights jdk 21 builds.
Fixes #1629
=> feat: JEP 445: Unnamed Classes and Instance Main Methods

src/main/java/dev/jbang/source/ProjectBuilder.java, src/main/java/dev/jbang/util/Util.java
=> fix: swallow any exceptions when setting file modified  timestamp

docs/modules/ROOT/pages/debugging.adoc, src/main/java/dev/jbang/catalog/Alias.java, src/main/java/dev/jbang/cli/KeyValueConsumer.java, src/main/java/dev/jbang/cli/Run.java, src/main/java/dev/jbang/cli/RunMixin.java, src/main/java/dev/jbang/source/CmdGeneratorBuilder.java, src/main/java/dev/jbang/source/generators/BaseCmdGenerator.java, src/main/java/dev/jbang/source/generators/JarCmdGenerator.java, src/test/java/dev/jbang/TestConfiguration.java, src/test/java/dev/jbang/cli/TestArguments.java, src/test/java/dev/jbang/cli/TestRun.java
fixes #1640 by allowing to override key/values.
The following "just works"
```
--debug
--debug=4004
--debug=suspend=y,server=n
--debug=server=n,address=*:4004
```
=> feat: --debug now allow multiple key/values. --debug=server=n,suspend=y

src/main/java/dev/jbang/dependencies/DependencyUtil.java, src/test/java/dev/jbang/source/TestTagReader.java
Fixes #1652 
Updates the regex `dev.jbang.dependencies.DependencyUtil#lenientGavPattern` to accept uppercase `groupId` and `artifactId`.
=> fix: allow uppercase group and artifactId names

src/main/java/dev/jbang/source/ProjectBuilder.java, src/main/java/dev/jbang/source/sources/GroovySource.java, src/main/java/dev/jbang/source/sources/KotlinSource.java, src/test/java/dev/jbang/source/TestSource.java
Before it would get added to Groovy and Kotlin as well.
Fixes #1656
=> fix: we now only add `-g` flag to Java source types

docs/modules/ROOT/pages/organizing.adoc
Make it more explicit that file paths need to be script-specific/relative
=> docs: make it more explicit that resource-paths need to be script-specific

readme.adoc
Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/jbangdevjbang/). Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project.
In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.
=> Link readme.adoc to project architecture diagrams

src/main/java/dev/jbang/source/ProjectBuilder.java, src/test/java/dev/jbang/cli/TestRun.java
Fixes #1684 
for the specific case of having module info but NO manifest then it fails.
this fixes that.
=> fix: check manifest exist before reading from it

src/main/java/dev/jbang/source/generators/JarCmdGenerator.java, src/test/java/dev/jbang/cli/TestRun.java
fixes #1689 
When a custom debug port is provided thanks to the parameter `--debug`, the port `4004` is still used.
* Ensure that the default values including the port can be redefined by the end user
* Add a unit test to cover the use case
=> fix: use the custom debug port when provided

misc/proxy/config/tinyproxy.conf, misc/proxy/docker-compose.yml
We can now test with proxies that require authentication.
=> test: updated docker-compose file for testing proxies

docs/modules/ROOT/pages/configuration.adoc, misc/proxy/README.md, misc/proxy/config/settings.xml, misc/proxy/docker-compose.yml
realized our docs were missing proxy config and our own testing missed the settings.xml settings.
should still make it better and require less setup as discussed in #1604 but this is a start.
=> docs: add docs for proxies and add settings.xml in proxy setup

src/main/java/dev/jbang/net/TrustedSources.java
I have added http inside trustedSource.startsWith .
=> fix: allow to mark http url as trusted

.github/workflows/publish-packages.yml, .github/workflows/tag-and-release.yml, build.gradle, jreleaser.yml
trying to get jreleaser to sign and publish to maven central.
=> feat: sign and publish jar to mavencentral

src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/cli/TestRun.java
=> feat: added support for `%{deps:...}` substitutions in arguments

src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/util/TestUtilDownloads.java
If the URL contained slashes in the parameter part of the URL, the filename extraction would fail.
Fixes #1740
=> fix: fixed filename extraction from URL

src/main/java/dev/jbang/cli/Edit.java
It was using existing, stale, Project instance to update the build file which resulted in the build file never actually being updated.
Fixes #1693
=> fix: Edit wasn't updating Gradle build files correctly

src/main/java/dev/jbang/cli/Init.java
Hi 👋  Happy New 2024!
I've just created a new script with `jbang init -t cli scripts/process_entries.java`
And I get as output:
```
[jbang] File initialized. You can now run it with 'jbang scripts/process_entries.java' or edit it using 'jbang edit --open=[editor] scripts/process_entries.java' where [editor] is your editor or IDE, e.g. 'code'. If your IDE supports JBang, you can edit the directory instead: 'jbang edit . 'scripts/process_entries.java. See https://jbang.dev/ide
```
The part about the directory is unclear to me and I believe there is a typo, which should read instead:
```
If your IDE supports JBang, you can edit the directory instead: 'jbang edit . '. 
```
(without the name of the script repeated _outside_ of the single quote command).
Hope this helps?
Sorry if the message …
=> fix: typo in edit message

build.gradle, src/main/java/dev/jbang/net/JdkProvider.java, src/main/java/dev/jbang/util/UnpackUtil.java
And get rid of javadoc and deprecation warnings.
=> chore: update deps

src/main/java/dev/jbang/source/CmdGeneratorBuilder.java, src/test/java/dev/jbang/cli/TestRun.java
Arguments passed to an alias are now appended to any arguments that are already defined in the alias instead of replacing them.
Fixes #605
=> feat!: alias arguments are now appended

src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/Catalog.java, src/main/java/dev/jbang/cli/Template.java
=> chore: made rendering of lists less noisy

itests/catalog.feature, src/main/java/dev/jbang/Configuration.java, src/main/java/dev/jbang/catalog/Alias.java, src/main/java/dev/jbang/catalog/Catalog.java, src/main/java/dev/jbang/catalog/CatalogRef.java, src/main/java/dev/jbang/catalog/CatalogUtil.java, src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java, src/main/java/dev/jbang/catalog/Template.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/Catalog.java, src/main/java/dev/jbang/cli/Template.java, src/main/java/dev/jbang/util/ConfigUtil.java, src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/TestImplicitAlias.java, src/test/java/dev/jbang/cli/TestAlias.java, src/test/java/dev/jbang/cli/TestAliasNearest.java, src/test/java/dev/jbang/cli/TestCatalog.java, src/test/java/dev/jbang/cli/TestCatalogNearest.java, src/test/java/dev/jbang/cli/TestTemplate.java
fix: properly listing the catalog names (fixes #1678)
feat: added --force options to catalog add commands (related to the above)
feat: added import feature to catalog refs
The last feature is something that we discussed (not sure if there's an issue for it, couldn't find it): an option that imports the items defined in a catalog and makes them available to the user without having to specify the full name, eg. using `@somecatalog`.
Right now this only works for local catalogs, so if you add a catalog reference with `jbang catalog add --import maxandersen` it will make all aliases, templates and catalog refs in that catalog available to the user without having to specify `@maxandersen`.
NB: The reason for the local catalog limitation (for now?) is to prevent a cascade. Otherwise you could …
=> Catalog command improvements

src/main/java/dev/jbang/util/Util.java, src/main/scripts/jbang
Title says it all. Now that Temurin has a GA JDK21 and ea versions on other openjdk release lines this will add support for Linux/riscv64.
Related: I was tempted to modify the default `JBANG_DEFAULT_JAVA_VERSION` for this platform to 21 instead of 17 in https://github.com/jbangdev/jbang/blob/826755c427070d2b69e88256a164658160bbedc6/src/main/scripts/jbang#L10C45-L10C46
This is because 21 is currently the only "GA" level at Adoptium. The 17 that is pulled down by default to bootstrap the process is an early access release. I'll leave it to reviewers to decide if that is a concern but I may raise a separate issue to consider bumping it to 21. I'll note that the obvious potential concern with doing that is that there are platforms (arm32) which is not available from Temurin in a GA JDK21 …
=> feat: add riscv64 support

src/main/java/dev/jbang/util/Util.java
The initial `jbang` shell script can download it's default JDK (Unless it detects an existing JDK on the system, when it will use the java version).
In all other cases, it sets the architecture to `unknown` so this PR will allow it to detect the 32-bit arm architecture properly.
Noting that this will generate a merge conflict with my riscv64 PR due to the `Arch` list but it's an easy merge :-)
Initially draft as I haven't test built it.
=> fix: 32-bit arm architecture detection missing

itests/catalog.feature, itests/template.feature, src/main/java/dev/jbang/catalog/Catalog.java, src/main/java/dev/jbang/catalog/CatalogUtil.java, src/main/resources/jbang-catalog.json, src/test/java/dev/jbang/cli/TestCatalogNearest.java
This is the simplest solution where we add the jbanghub catalog ref to the "builtin" catalog. It does mean however that a user could never remove it (they could override it, for example to make it non-importing, but they could not remove it).
=> feat: added jbanghub to builtin catalog

build.gradle, src/main/java/dev/jbang/cli/JBang.java, src/test/java/dev/jbang/cli/TestRun.java
=> fix: no longer get an exception when using option names as values

src/main/java/dev/jbang/cli/App.java
Currently `jbang app list` prints out all the files in the bin directory. This PR fixes this by filtering the files by the executable flag (scripts in PATH are picked up by the shell only if they're executable anyways)
=> Make 'app list' only return executables

itests/shellenv.feature, src/main/scripts/jbang, src/main/scripts/jbang.cmd, src/main/scripts/jbang.ps1
It's *really* hard (impossible?) to find the location of the script that launched the JVM from within jbang. It would be really useful to be able to do that so you can run jbang again with some logic to precompute the command line. This works really simply:
```
$ jbang --interactive
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
|  Welcome to JShell -- Version 17.0.7
|  For an introduction type: /help intro
jshell> System.getenv("JBANG")
$1 ==> "/home/dsyer/.sdkman/candidates/jbang/current/bin/jbang"
```
Edit: I don't know how to do this for Windows users. Anyone got an idea?
=> feat: export an additional env var pointing to the location of jbang

build.gradle, docs/modules/ROOT/pages/dependencies.adoc, src/main/java/dev/jbang/dependencies/ArtifactResolver.java
A new ArtifactType that is also present in Maven4. The 'fatjar' type denotes a Java JAR file that is
"self sufficient", contains all the dependencies. This makes resolver stop resolving. Usable when for example there is an `uber` or `cli` classified artifact, as in other cases resolver would pick up POM and (probably wrongfully) resolve it.
Fixes #1778
Alows something like this
```
$ jbang eu.maveniverse.maven.plugins:toolbox:0.1.9:cli@fatjar
```
Note: Maven4 introduced this type, but Maven3 has no idea about it. JBang uses new feature of MIMA that allows one to define own ArtifactTypes. See https://github.com/apache/maven/pull/1459
=> feat: introduce type 'fatjar'

src/main/java/dev/jbang/cli/Version.java
Added a couple of more informational lines that can help us debug issues that people might have with JBang.
=> chore: made `version --verbose` more verbose

src/main/java/dev/jbang/net/jdkproviders/JBangJdkProvider.java
in https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/JBang.20failure/near/455708888 @gsmet had this happen:
```
Error:  [ERROR] JDK version is not available for installation: 21
Use 'jbang jdk list --available' to see a list of JDKs available for installation
[jbang] Run with --verbose for more details
Error: Process completed with exit code 2.
```
as it happens in github he can't really easily re-run with verbose to get info why failed.
This PR tries without having to reorganize the whole call chain and print out last possible exception for each provider.
=> feat: when no jdk installable show possible reasons/erros

src/main/java/dev/jbang/net/JdkManager.java, src/main/java/dev/jbang/net/JdkProvider.java, src/main/java/dev/jbang/net/jdkproviders/BaseFoldersJdkProvider.java, src/main/java/dev/jbang/net/jdkproviders/LinuxDistroJdkProvider.java, src/main/java/dev/jbang/net/jdkproviders/LinuxJdkProvider.java, src/test/java/dev/jbang/cli/TestJdk.java
adds `linuxdistro` provider which for now searches `/usr/lib/jvm` for jdks.
It is not enabled by default as it is not possible to safely determine the version and build of the jdk
present or needed to be installed if mising.
Meaning to get it user need to run `jbang config set jdkproviders all` or `jbang config set jdkproviders linuxdistro` if only want this.
You can see which providers are finding jdks by running `jbang jdk list --show-details`
Fixes #1825 
@quintesse I see that `jbang jdk list --show-details` list what looks like all dirs even though javac is not available. is that expected?
=> feat: linuxdistro jdk provider

build.gradle, docs/modules/ROOT/pages/javaversions.adoc, docs/modules/ROOT/pages/usage.adoc, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/cli/Jdk.java, src/main/java/dev/jbang/net/JdkManager.java, src/main/java/dev/jbang/util/Util.java, src/main/scripts/jbang.ps1, src/test/java/dev/jbang/cli/TestJdk.java
=> feat: we can now create junctions on Windows

src/main/java/dev/jbang/source/buildsteps/CompileBuildStep.java, src/main/java/dev/jbang/source/buildsteps/NativeBuildStep.java, src/main/java/dev/jbang/source/generators/BaseCmdGenerator.java, src/main/java/dev/jbang/source/generators/JarCmdGenerator.java, src/main/java/dev/jbang/util/CommandBuffer.java
We were already doing this for the `java` command, but not for the `javac` and `native-image` commands becuase they were run using the `ProcessBuilder` API and it turns out it has a limit of 32K characters on Windows.
Fixes #1861
=> fix: fixes issue with too long command lines on windows

build.gradle, src/main/java/dev/jbang/dependencies/ArtifactResolver.java
Issue is related how Maven3 works, as JBang creates "fake" root and adds direct dependencies to it. This in Maven3 implies that depMgmt entries of added dependencies are NOT applied.
Example: `jbang io.quarkus:quarkus-tls-registry:jar:3.15.1` will use Jackson 2.16... instead of wanted 2.17...
Fix: I missed that depMgmt of BOMs is already slurped up, so basically just do the same to **all deps**, while BOMs are added first (to prevail). ~~Also, no need to "apply" depMgt and any sort of magic, just let Resolver it's job.~~ There is need for magic, as unlike Maven, JBang allows use of GA and will deduce V from BOM.
Example now uses Jackson 2.17... as can be seen in gist w/ PR applied locally:
https://gist.github.com/cstamas/024db87af357b658492a9d9b60857bfa
=> fix: fix dependency resolution re depMgmt

src/jreleaser/distributions/jbang/docker/Dockerfile.tpl
fixes https://github.com/jbangdev/jbang/issues/1831 by creating the empty dir so jshell stops nagging.
=> fix: avoid noisy jshell logging in dockerfile

CONTRIBUTING.adoc
the build is not working with Java 17 and Java 21
Java 11 is used on CI
=> docs: add prerequisite Java 11 version to build

src/main/java/dev/jbang/util/Util.java
=> feat: Improve error message to know where to place --verbose option

docs/modules/ROOT/pages/dependencies.adoc, src/main/java/dev/jbang/dependencies/JitPackUtil.java, src/test/java/dev/jbang/dependencies/TestJitPack.java
https://github.com/jbangdev/jbang/issues/1817 made me bite the bullet and have github urls default to use `main-SNAPSHOT` so it wont fail on new stuff. The whole reason I hesitated was that jitpack in past would accept HEAD-SNAPSHOT to pickup whatever is the default name on github (main or master). But that stop working some years ago - back then I hoped it was just a glitch..but since not fixed i'm now at least making it work for new things.
also updated the docs and added more tests as things were slightly incorrect.
Fixes #1817
=> fix: use main-SNAPSHOT as best-effort fallback for jitpack

docs/modules/ROOT/pages/dependencies.adoc
Very small change to replace TAB with 4 spaces.
=> docs: Fix whitespace in dependencies.adoc

src/main/java/dev/jbang/Main.java, src/main/java/dev/jbang/source/resolvers/RenamingScriptResourceResolver.java, src/test/java/dev/jbang/cli/TestRun.java
FIrst of all JBang will now correctly handle trying to run `jbang --preview somefile.java` and secondly the message when unsuccessfully trying to run a folder (eg `jbang --preview .`) will now mention `build.jbang` (before it would only mention `main.java`).
And finally running `jbang --preview .` will now actually work if the folder contains a `build.jbang` file.
=> Fixes for --preview option and using build.jbang

.github/workflows/ci-build.yml, .github/workflows/report.yml, src/main/java/dev/jbang/source/ProjectBuilder.java, src/test/java/dev/jbang/source/TestProjectBuilder.java
I've [had enough ](https://github.com/mariofusco/site-summarizer/pull/2) with java not by default adding `-parameters` 
since java 8 `-parameters` been supported and if you use any Quarkus, Spring, Micronaut or any other annotation driven framework or library you need `-parameters` to have functional code.
Only downside I can think of is that the bytecode gets slightly bigger and pre-Java 8 code that somehow assumes names starts with "argN" breaks - that is minuscule impact  IMO.
But it is what kept me from adding it until now.
Now I'm realizing that it actually is worse to NOT include it due to so many libraries requiring it and having to tell everyone to include `//JAVAC_OPTIONS -parameters` to fix possible obscure errors is not worth worth.
we do the same for `-g` (debug symbols) and …
=> ensure -parameters is set for javac

itests/noints.java, src/main/java/dev/jbang/catalog/Alias.java, src/main/java/dev/jbang/cli/Alias.java, src/main/java/dev/jbang/cli/BaseBuildCommand.java, src/main/java/dev/jbang/cli/BuildMixin.java, src/main/java/dev/jbang/source/AppBuilder.java, src/main/java/dev/jbang/source/Project.java, src/main/java/dev/jbang/source/ProjectBuilder.java, src/main/java/dev/jbang/source/Source.java, src/test/java/dev/jbang/cli/TestRun.java, src/test/java/dev/jbang/source/TestBuilder.java
realized #1776 didn't require much for the first MVP.
adds a `--no-integrations` option to disable execution of integrations.
=> feat: add --no-integrations option

src/main/scripts/jbang.ps1
This avoid a half second of friction when adding the wrapper to projects with like to trim whitespace at the end of lines, using e.g. tools like [`.editorconfig`](https://editorconfig.org/) with trim_trailing_whitespace = true` enforced e.g. with https://pre-commit.com.
=> Remove spurious line endings in Wrapper's Powershell script

docs/modules/ROOT/pages/javaversions.adoc
I propose to add this command to the documentation so that the user can check the available versions without leaving this terminal.
=> Add `jbang jdk list --available` in javaversions.adoc

docs/modules/ROOT/pages/javaversions.adoc
Replace https://adoptopenjdk.net/releases.html with https://adoptium.net/temurin/releases, in javaversions.adoc, to be up to date with AdoptOpenJDK moving to the Eclipse foundation. In fact, when we open https://adoptopenjdk.net/releases.html, we get this message: 
> 24th July 2021: AdoptOpenJDK is moving to the Eclipse Foundation and rebranding.
> Our July 2021 and future releases will come from Adoptium.net
=> docs: Update Adoptium URL in javaversions.adoc

src/main/java/dev/jbang/dependencies/ArtifactResolver.java
If there are no deps (or only imports, which does not make sense), do not belly up. Also, make sure that all the refd POMs (of deps and imports) are present, as by def Maven uses "forgiving" policy.
=> fix: if no deps, avoid npe; also make sure POMs refd exist

src/main/java/dev/jbang/source/CmdGeneratorBuilder.java, src/main/java/dev/jbang/source/ProjectBuilder.java, src/main/java/dev/jbang/source/generators/JarCmdGenerator.java, src/test/java/dev/jbang/cli/TestRun.java
fixes #1852
make it now trivial to run things like: `fish.payara.extras:payara-micro:LATEST` and `com.google.googlejavaformat:google-java-format:RELEASE`
opening in draft as I haven't figured a reliable way to avoid the add opens to be skipped when running on older than java 9.
=> feat: honor add-opens/exports from jar manifest

src/main/scripts/jbang
See https://www.shellcheck.net/wiki/SC2086 & https://www.shellcheck.net/wiki/SC2155.
=> Fix a few ShellCheck SC2086 & SC2155 in Wrapper's Linux script

.justfile
The actions for opening a web browser with the results from the tests didn't work on Windows. Now it does.
=> chore: fix justfile for windows

docs/modules/ROOT/pages/exporting.adoc, itests/classpath_log_bom.java, itests/exporttags.java, src/main/java/dev/jbang/cli/Export.java, src/main/resources/export-build.qute.gradle, src/main/resources/export-pom.qute.xml, src/test/java/dev/jbang/cli/TestExport.java
My initial attempt to fix #1044. I know there are still rough edges but at least the following basic usages work. Let me send it for your review so that I can check I'm on the right track.
Add two subcommands to 'jbang export':
* jbang export maven
* jbang export gradle
Those generate a template maven/gradle project the user can start developing the script further.
Fix #1044
Usage examples:
```console
jbang export maven hello.java # generates hello/ project with org.example.project:hello:999-SNAPSHOT
jbang export gradle -g dev.jbang.hello -a hello -v 1.0.0 -O hello2 hello.java # generates hello2/ with dev.jbang.hello:hello:1.0.0
```
=> feat: export maven/gradle project

.github/workflows/ci-build.yml
github action tj-actions/verify-changed-files was comprimised in this pr https://github.com/tj-actions/changed-files/pull/2460
we use sha's for our github actions to exactly not be exposed to this kind of issues.
Other alternative is to not use random github actions and for this usecase of detecting file changes we don't actually seem to need an action.
So thats what this PR does :)
=> fix: export maven/gradle should not touch default packages

src/main/java/dev/jbang/catalog/Alias.java, src/test/java/dev/jbang/cli/TestCatalog.java
with #1800 its useful to use @fatjar in catalogs for i.e.  io.quarkiverse.mcp:quarkus-mcp-stdio-sse-proxy:1.0.0.Beta5@fatjar
without it lots of unnecessary dependencies are fetched.
But turns out catalogs were merging aliases when there was just any @ in the name - ignoring  it could be possible GAV.
GAV's has :'s and version in specific places which i don't think will be confused for catalog names...but lets check :)
=> fix: do not assume @ always means catalog

itests/exporttags.java, src/test/java/dev/jbang/cli/TestExport.java
#1044  added test with `//JAVA 21+` which adds about 20-30 seconds to the runtime of TestExport as it triggers autodownload of java 21 on at least 2 unittests methods.
made it use 11+ instead and things won't be as bad unless you run with 8 :)
=> fix: avoid downloading java 21 for no good reason

src/main/java/dev/jbang/util/Util.java, src/test/java/dev/jbang/util/NoOpUrlConnection.java, src/test/java/dev/jbang/util/TestUtil.java, src/test/resources/url.properties
This pull request adds support for Basic Auth credentials in the catalog-ref url. They will take precedence over JBANG_AUTH_BASIC_USERNAME/JBANG_AUTH_BASIC_PASSWORD env variables.
#1886
=> feat: support Basic Auth in the catalog-ref URL (#1886)

.justfile, docs/modules/cli/pages/jbang-export-gradle.adoc, docs/modules/cli/pages/jbang-export-maven.adoc, docs/modules/cli/pages/jbang-jdk.adoc, docs/modules/cli/partials/nav-jbang.adoc, src/main/java/dev/jbang/cli/Jdk.java
tired of forgetting its java-env and not just env.
keeps things backwards compatible.
=> fix: allow env as alias for java-env

src/main/java/dev/jbang/util/UnpackUtil.java, src/main/java/dev/jbang/util/Util.java
if you try something like ` JBANG_JDK_VENDOR=graalvm just jbang --java 23 --native --verbose pcli.java` you get an error about native-image permissions.
turns out graalvm targz files has symbolic links for native-image which we don't currently honor - as no other JDK seem to do this.
This fixes that.
=> fix: handle symbolic links in untar

src/main/java/dev/jbang/cli/Export.java, src/main/java/dev/jbang/source/Source.java, src/main/java/dev/jbang/source/buildsteps/CompileBuildStep.java, src/main/java/dev/jbang/source/sources/GroovySource.java, src/main/java/dev/jbang/source/sources/JavaSource.java, src/main/java/dev/jbang/source/sources/JshSource.java, src/main/java/dev/jbang/source/sources/KotlinSource.java, src/main/java/dev/jbang/source/sources/MarkdownSource.java, src/test/java/dev/jbang/cli/TestRun.java
There was a bit too many instanceof tests for my taste so I made the `Source` return its `Type` (that was an existing type but it wasn't being exposed) and extended the `Type` to include the "maven source folder" name (which is the name of the folder that sources should be in when using the maven project structure, eg: "src/main/**java**")
I also made sure that the code will exit with an error when trying to export an unsupported language (especially useful now that people are looking to support other languages like Python/Jython)
=> chore: minor export cleanup/improvements

docs/modules/ROOT/pages/alias_catalogs.adoc
Update documentation of alias command to describe how to leverage `--description` CLI switch or `//DESCRIPTION` tag.
Closes #861
=> docs: Describe //DESCRIPTION

src/main/java/dev/jbang/util/CommandBuffer.java, src/test/java/dev/jbang/util/TestCommandBuffer.java
When using the CommandBuffer on Windows to create a ProcessBuilder the code would take into account the Shell that JBang was run from. But in the case of a ProcessBuilder the Shell is irrelevant and we should always assume CMD.
Fixes #1974
=> fix: Fix CommandBuffer when running on Windows from bash

src/it/java/dev/jbang/it/BaseIT.java, src/it/java/dev/jbang/it/JarIT.java
Some itests leave create files in the project folder and leave them around.
This then complicates committing any changes because you have to be careful that you don't accidentally commit those files as well.
These changes avoid that by making a temporary copy of the entire itests folder and run the tests from there.
Also fixed one test that I guess depended on the order that the tests were run in because there doesn't exist a `helloworld.jar` in the itests folder.
=> test: make sure itests leave project directory clean

src/main/java/dev/jbang/Configuration.java, src/main/java/dev/jbang/source/DirectResourceRef.java, src/main/java/dev/jbang/source/LazyResourceRef.java, src/main/java/dev/jbang/source/ProjectBuilder.java, src/main/java/dev/jbang/source/ResourceRef.java, src/main/java/dev/jbang/source/ResourceResolver.java, src/main/java/dev/jbang/source/resolvers/AliasResourceResolver.java, src/main/java/dev/jbang/source/resolvers/ClasspathResourceResolver.java, src/main/java/dev/jbang/source/resolvers/CombinedResourceResolver.java, src/main/java/dev/jbang/source/resolvers/FileResourceResolver.java, src/main/java/dev/jbang/source/resolvers/GavResourceResolver.java, src/main/java/dev/jbang/source/resolvers/LazyResourceResolver.java, src/main/java/dev/jbang/source/resolvers/LiteralScriptResourceResolver.java, src/main/java/dev/jbang/source/resolvers/RemoteResourceResolver.java, src/main/java/dev/jbang/source/resolvers/RenamingScriptResourceResolver.java, src/main/java/dev/jbang/source/resolvers/SiblingResourceResolver.java, src/test/java/dev/jbang/source/TestProjectBuilder.java, src/test/java/dev/jbang/source/TestSourcesMultipleSomeMissingFiles.java, src/test/java/dev/jbang/source/TestSourcesRecursivelyMultipleFiles.java
Turned `ResourceRef` into an interface and added `LazyResourceRef` and `LazyResourceResolver` to allow for lazy loading of resources. This is especially useful for those resources that we don't need to download locally, but where we are only interested in the original resource reference (mostly the case for URLs).
=> refactor: Added `LazyResourceRef`

src/main/java/dev/jbang/cli/App.java, src/main/java/dev/jbang/cli/Edit.java, src/main/java/dev/jbang/source/buildsteps/CompileBuildStep.java, src/main/java/dev/jbang/source/buildsteps/NativeBuildStep.java, src/main/java/dev/jbang/source/generators/BaseCmdGenerator.java, src/main/java/dev/jbang/source/generators/JarCmdGenerator.java, src/main/java/dev/jbang/source/sources/GroovySource.java, src/main/java/dev/jbang/source/sources/JavaSource.java, src/main/java/dev/jbang/source/sources/KotlinSource.java, src/main/java/dev/jbang/util/CommandBuffer.java, src/test/java/dev/jbang/util/TestCommandBuffer.java
On Windows when using Java's `ProcessBuilder` to run .bat or .cmd files we have to ensure that the command line does not exceed the maximum length allowed by the Windows command line.
Fixes #2033
=> fix: handle long command lines for .bat and .cmd

itests/repos.java, src/main/java/dev/jbang/cli/App.java, src/test/java/dev/jbang/cli/TestApp.java
Because "app install" pre-builds the app that it installs, it's not
enough to only copy the build options to the installed app startup
script, but they also need to be passed to the pre-build process and
that was missing.
Fixes https://github.com/jbangdev/jbang/issues/2043
also:
feat: added --no-build option to app install
=> fix: pass `app install` build options to pre-build process

src/main/java/dev/jbang/cli/ScriptMixin.java
while testing the fix for #1975 I got tired of typing out `--source-type java` all the time so thought `-t` would be good to have as option.
not merging it directly as `-t` could probably be used for lot of other things ... so if other suggestions on ways we could avoid having to always fully type `--source-type` i'm all ears....otherwise lets merge it as #1975 actually is quite useful now that it actually works ;)
=> fix: add -t as short hand for --source-type

docs/modules/ROOT/pages/installation.adoc
=> docs: removed icons in sdkman heading not supported by antora

src/main/java/dev/jbang/dependencies/DependencyUtil.java
Add jogamp maven repo short cut to make it easier to use processing.org maven artifacts that relies on jogamp.
=> feat: add  as repo shortcut for jogamp.org maven repo

build.gradle, src/main/java/dev/jbang/Cache.java, src/main/java/dev/jbang/cli/Info.java, src/main/java/dev/jbang/cli/Jdk.java, src/main/java/dev/jbang/source/Project.java, src/main/java/dev/jbang/util/JavaUtil.java, src/test/java/dev/jbang/cli/TestJdk.java
The latest version of devkitman supports setting the "distro" of the JDK to install, which allows us to use the `JBANG_JDK_VENDOR` environment variable again to select the JDK vendor. Which was a feature that was missing since the switch to devkitman. (In devkitman the term "distro" was chosen instead of "vendor".)
=> fix: `JBANG_JDK_VENDOR` can again be used

build.gradle, readme.adoc, settings.gradle
avoids me having to remember to set java version before build :) 
@quintesse seeing any issue using java 11 as default as it can compile to 8 ?
=> chore: enable toolchain for gradle using java 11

src/it/java/dev/jbang/it/BaseIT.java, src/main/java/dev/jbang/Main.java, src/main/java/dev/jbang/cli/JBang.java, src/main/java/dev/jbang/util/Util.java
The setup of help information for PicoCli is now done lazily which improves JBang startup time in general but specifically on systems that for some reason are slow when scanning the PATH for plugins. We also improved direct plugin lookup by not using full file scanning.
See #2147 and #2137
=> fix: this fixes part of the slowness on startup

src/main/java/dev/jbang/cli/App.java
Should fix #2189.
But I've written this "blindly", and not actual run it.
@maxandersen during development, how do I make it "do the same thing that `curl -Ls https://sh.jbang.dev | bash -s - app setup` would do", to test? What `./gradlew ...` do I need to run to get a `jbang` somewhere? And then launch it as ... what, `???/jbang app setup`, presumably?
Let's get #2190 merged first, so that I can rebase this and it only has the actual fix.
Draft, for now; until I've actually been able to test it.
=> fix: Install adds ~/.jbang/bin to PATH via .config/fish/conf.d/jbang.fish

src/main/java/dev/jbang/cli/Init.java, src/main/resources/init-agent.java.qute, src/main/resources/init-cli.java.qute, src/main/resources/init-hello.groovy.qute, src/main/resources/init-hello.java.qute, src/main/resources/init-hello.kt.qute, src/main/resources/init-readme.md.qute
alternative/replacement of #2143 
in #2143 it was suggested to force add "//JAVA 25+" when compact source enabled (automatically enabled when Java > 25) but I turned it down as it was resulting in inconsistent behavior.
Since then I myself been caught by having done `jbang init --java 25 hello.java` and then when running `./hello.java` it didn't work because my environments java was less than Java 25.
so this PR suggests introducing a `requestedJavaVersion` property which will be set to null if no specific java version requested; and other set to the raw string of the arg value in `--java <arg>`
Then use that to generate `//JAVA ${requestedJavaVersion}` if requested version is present, and in the case of compact source files will get `//JAVA 25+` if you did not request a specific java …
=> feat: requestedJavaVersion honored by init templates

itests/runkotlin.kt, src/test/java/dev/jbang/cli/TestEdit.java, src/test/java/dev/jbang/cli/TestRun.java, src/test/java/dev/jbang/dependencies/DependencyResolverTest.java
used the perf graph in allure report to identify the top candidates for tests being slow.
reduced 3-4 tests of 15-30s length due to excessive dependency fetching which was not really needed for what they tested.
=> fix: make tests faster by doing less

bootstrap.sh
fixes #2192 
instead of having manual update deps I call out to gradle to get the deps. 
makes the bootstrap.sh less clean/independent but you can always remove that line and just have the deps listed specifically.
=> fix: make bootstrap.sh harder to break

docs/modules/ROOT/pages/configuration.adoc
The syntax for JVM parameters only requires a single "-D".
=> docs: Fix JVM proxy args
