examples/webdriver.java

Very basic Selenium WebDriver example using WebDriverManager https://github.com/bonigarcia/webdrivermanager

example using webdriver

---

src/main/java/dk/xam/jbang/Main.java
src/test/java/dk/xam/jbang/TestMain.java

added support for bitbucket urls.
`jbang https://bitbucket.org/Shoeboom/test/src/master/helloworld.java` --> `jbang https://bitbucket.org/Shoeboom/test/raw/master/helloworld.java`

added bitbucket

---

.gitpod.Dockerfile
.gitpod.yml
readme.adoc

this commit adds support for Gitpod.io, a free automated
dev environment that makes contributing and generally working on GitHub
projects much easier. It allows anyone to start a ready-to-code dev
environment for any branch, issue and pull request with a single click.

Add gitpod config

---

build.gradle
src/main/java/dk/xam/jbang/DependencyUtil.java
src/main/java/dk/xam/jbang/Main.java
src/main/java/dk/xam/jbang/Settings.java
src/test/java/dk/xam/jbang/DependencyResolverTest.java
src/test/java/dk/xam/jbang/TestAddDeps.java

Why:
* really want to support ~/.m2/settings.xml
This change addreses the need by:
* revert shrinkwrap reversal
* use default transitive no-optional strategy
(this is a breaking change)

revert back to shrinkwrap take 2

---

.github/workflows/ci-build.yml
build.gradle
examples/progress.java
examples/resteasyclient.java
itests/quote.java
itests/test_suite.sh
otp.java
src/main/scripts/jbang

Handle quotes better in jbang

---

src/main/resources/launch.qute.json

Remove broken and redundant vscode launch config

---

src/main/resources/settings.qute.json

to reduce clutter
* Before:
* After:

Hide non-relevant files in vscode

---

readme.adoc

docs: remove incorrect header markup

---

src/main/java/dev/jbang/Settings.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/test/java/dev/jbang/cli/TestAlias.java

Hi @maxandersen , could you merge this? I saw you fixed an issue with the usage of `getAlias()`, but it was actually a problem in `getAlias()` itself.

Minor refactor in usage of `getAlias()`

---

examples/update_catalog.java
jbang-catalog.json
src/main/java/dev/jbang/Settings.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/Alias.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/main/java/dev/jbang/cli/Catalog.java
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/cli/Jbang.java
src/main/java/dev/jbang/cli/Run.java
src/test/java/dev/jbang/TestUtil.java
src/test/java/dev/jbang/cli/TestAlias.java
src/test/java/dev/jbang/cli/TestCatalog.java
src/test/java/dev/jbang/cli/TestInit.java

Adds support for Catalogs

---

src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/main/java/dev/jbang/cli/Build.java
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/cli/Jbang.java
src/main/java/dev/jbang/cli/Run.java

Was tinkering with #62 by adding a super naive "build" command
that is exactly the same as Run but just don't do run part.
When I noticed --insecure used for downloading was only applied to Run and
no other commands...should get that moved more central.

Add build command + move insecure to base. Fixes #62

---

src/main/java/dev/jbang/AliasUtil.java
src/main/java/dev/jbang/JdkManager.java
src/main/java/dev/jbang/TrustedSources.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/BaseCommand.java
src/main/java/dev/jbang/cli/Jbang.java
src/main/java/dev/jbang/cli/Run.java

Mostly for implicit catalogs and JDK management.
Should be safe to merge @maxandersen , it at least makes the process of installing JDKs and finding implicit catalogs a bit less "magical" :-)

Added a bunch of verbose debug messages to the code.

---

src/main/java/dev/jbang/AliasUtil.java
src/main/java/dev/jbang/JdkManager.java
src/main/scripts/jbang
src/main/scripts/jbang.cmd

WIP: Implemented bootstrapping of Jbang when Java is not available

---

src/main/java/dev/jbang/AliasUtil.java
src/main/java/dev/jbang/Util.java

Using this for debugging now, but perhaps it's useful to merge into master?

Show stacktrace when implicit download attempts fail and verbose is on

---

src/main/java/dev/jbang/JdkManager.java
src/main/java/dev/jbang/Settings.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/main/java/dev/jbang/cli/Cache.java
src/main/java/dev/jbang/cli/Jdk.java
src/test/java/dev/jbang/cli/TestArguments.java

Implements different cache types that can be cleared separately.

---

src/main/java/dev/jbang/JavaUtil.java
src/main/scripts/jbang
src/main/scripts/jbang.cmd

These 2 commits result in about a 17% improvement. It's something , but it's not enough.
Even just asking Jbang for its version 10 times takes almost 7s on my system:
```
$ time zsh -c "repeat 10 ./build/install/jbang/bin/jbang version"
6,72s user 0,51s system 208% cpu 3,475 total
```
(this is with these 2 commits, which actually resulted in a 33% reduction)

WiP: Improve Jbang startup performance

---

itests/cache.feature
src/main/java/dev/jbang/JdkManager.java
src/main/java/dev/jbang/Settings.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/main/java/dev/jbang/cli/Cache.java
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/cli/Run.java

Added `projects`, `scripts` and `stdins` cache classes

---

src/main/java/dev/jbang/Util.java
src/main/scripts/jbang

Added `aarch64` to list of supported architectures

---

build.gradle
examples/analytics.java
examples/asciidoc.java
examples/asciidoctor.java
examples/camel.java
examples/checksum.java
examples/envdetector.java
examples/findmodule.java
examples/gh_fetch_release_assets.java
examples/imap.java
examples/progress.java
examples/resteasyclient.java
examples/shrinkwrap.java
examples/smee.java
examples/tz.java
examples/update_catalog.java
itests/jar.feature
itests/quote.java
otp.java
readme.adoc
src/main/resources/init-cli.java.qute
src/main/scripts/choco/jbang.nuspec
src/main/scripts/spec/jbang.spec
src/test/java/dev/jbang/cli/TestAddDeps.java
src/test/java/dev/jbang/cli/TestRun.java

Release notes: https://github.com/remkop/picocli/releases/tag/v4.5.0

Bump to Picocli 4.5.0

---

itests/itests.cmd
itests/itests.sh
itests/run.feature
itests/test_suite.sh
readme.adoc
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/cli/Init.java
src/main/java/dev/jbang/cli/Run.java

Add --jfr for easy flight recording

---

src/main/scripts/jbang.cmd

Also removed some tabs from the file

Made powershell invocations a bit more robust

---

readme.adoc

Using https://www.eclipse.org/che/contribute.svg
See eclipse/che#17758

Update 'Developer workspace' badge image

---

src/main/java/dev/jbang/Script.java

This allows Quarkus class transformation to work

Put jar at the start of the class path

---

itests/karate-config.js
itests/wrapper.feature
src/main/java/dev/jbang/cli/BaseCommand.java
src/main/java/dev/jbang/cli/Jbang.java
src/main/java/dev/jbang/cli/Wrapper.java
src/main/scripts/jbang
src/main/scripts/jbang.cmd

This copies the startup files and the JAR file to either the current directory or the specified one.

Install wrapper

---

src/main/java/dev/jbang/cli/Edit.java

Support space separated string as liveeditor

---

src/main/scripts/jbang

That was a lot of work for a single-word fix! :roll_eyes: 
For #283

Fixes #283 "javac not found" error

---

readme.adoc

https://www.oracle.com/java/technologies/javase/jdk-11-relnote.html#JDK-8192920

Java 11 supports running .java files directly

---

src/main/java/dev/jbang/JdkManager.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java

fix: Revert "fix: made downloading more robust"

---

src/main/scripts/jbang
src/main/scripts/jbang.cmd

This will set the Java version to download when NO Java is available

feat: Added `JBANG_DEFAULT_JAVA_VERSION`

---

src/main/java/dev/jbang/JavaUtil.java

Before if the user asked for "12+" and "14" was installed
version 12 would still be downloaded, installed and used.
This is now fixed.

fix: Fixed requesting open-ended Java versions

---

build.gradle
src/main/java/dev/jbang/Script.java
src/main/java/dev/jbang/ScriptResource.java
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/test/java/dev/jbang/cli/TestRun.java

Initial basic support for fetching //SOURCES relative to scripts fetched from http(s) etc.
p.s. doesn't yet handle downloads via urls that redirects...tbd
Fixes #328

feat: add support for multiple source files via https

---

src/main/java/dev/jbang/DependencyUtil.java
src/main/java/dev/jbang/Script.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java

It will now also silence the dependency resolving.

fix: Improved`--quiet` option

---

readme.adoc

Adds small description of JBANG_DEFAULT_JAVA_VERSION usage to readme.

Adds JBANG_DEFAULT_JAVA_VERSION details to readme

---

src/main/java/dev/jbang/cli/Jdk.java
src/test/java/dev/jbang/cli/TestJdk.java

Adds more friendly messages for 'jdk list' and 'jdk uninstall' adding
feedback for users.
Fixes #347

feat: improves jdk command output messages

---

src/main/java/dev/jbang/AliasUtil.java
src/test/java/dev/jbang/cli/TestAlias.java
src/test/java/dev/jbang/cli/TestAliasWithBaseRef.java

fix: jbang alias now again works with GAV refs

---

src/main/java/dev/jbang/Main.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/Run.java

refactor: minor code simplifications

---

.github/PULL_REQUEST_TEMPLATE.md

GH template for PRs with info about Conventional Commits
When I created my first PR I wasn't 100% what's needed to make `Semantic Pull Request` check pass.
GH PR template should help newcomers to get to the right info quickly.
I know https://github.com/zeke/semantic-pull-requests is mentioned in CONTRIBUTING.adoc but it wasn't clear to me there were implications I should follow in my PR. Plus who reads the whole CONTRIBUTING.adoc file :)

chore: GH template for PRs with info about Conventional Commits

---

CONTRIBUTING.adoc

Some minor suggestions that I noticed while using this great build-pipeline as a reference. Feel free to reject if doesn't look right :). Thanks!
Thanks for submitting your Pull Request!

docs: minor updates to contributing.adoc

---

readme.adoc

Add Cheatsheet section to readme.adoc

---

src/main/scripts/jbang.ps1

fixes #397
If in doubt then open the pull-request and we'll help you - Thank you!

fix: temporary dir now properly set in jbang.ps1

---

src/main/java/dev/jbang/ModularClassPath.java
src/main/java/dev/jbang/Script.java
src/main/java/dev/jbang/TrustedSources.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/Catalog.java
src/main/java/dev/jbang/cli/Completion.java
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/cli/Jbang.java
src/main/java/dev/jbang/cli/Run.java
src/test/java/dev/jbang/TestScript.java
src/test/java/dev/jbang/cli/TestAlias.java
src/test/java/dev/jbang/cli/TestArguments.java
src/test/java/dev/jbang/cli/TestEdit.java
src/test/java/dev/jbang/cli/TestInit.java
src/test/java/dev/jbang/cli/TestRun.java

fix: cleanup based on eclipse IDE findings

---

src/main/java/dev/jbang/cli/Alias.java
src/test/java/dev/jbang/cli/TestAlias.java

fix: Default alias name when creating a new alias

---

src/main/java/dev/jbang/cli/Edit.java
src/main/resources/README.qute.md
src/test/java/dev/jbang/cli/TestEdit.java

fix: add readme.md to edit fixes #210

---

itests/catalog.feature
readme.adoc
src/main/java/dev/jbang/AliasUtil.java
src/main/java/dev/jbang/Settings.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/Alias.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/main/java/dev/jbang/cli/Catalog.java
src/test/java/dev/jbang/TestUtil.java
src/test/java/dev/jbang/cli/TestAliasNearest.java
src/test/java/dev/jbang/cli/TestAliasNearestWithBaseRef.java
src/test/java/dev/jbang/cli/TestCatalog.java
src/test/java/dev/jbang/cli/TestCatalogNearest.java

Implements the features mentioned in #406 
Still needs

feat: Implement local catalog indices

---

readme.adoc

'edit' added to live editing example

docs: 'edit' added to live editing example

---

src/main/java/dev/jbang/Util.java
src/test/java/dev/jbang/TestUtil.java

Hi,
This patch fix/enhance the check that a String contains `main` method.
It is probably not exhausting, but it is much better than what I did before.

fix: better check for String contains main method

---

src/main/java/dev/jbang/ScriptResource.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/test/java/dev/jbang/TestScript.java

This PR add a test that was not merged from #469 
It also extract the logic to a method, making it easier to test and the code more readable.
There's also a fix: if it's a URL in //SOURCES, then the URL itself it's the `thingToFetch`.

test: Add test for find //SOURCES and //DEPS recursively

---

src/test/java/dev/jbang/TestScript.java
src/test/java/dev/jbang/TestSourcesRecursivelyMultipleFiles.java

PR #469 enable to search //SOURCES in multiple files, but I didn't tested subfolder and different paths, and there's a bug.
Error:
```java
$ ./jbang/bin/jbang --verbose /home/leandro/dev/java/jbang/scripts/test-multiple-child-folders-package/A.java
[jbang] [ERROR] /home/leandro/dev/java/jbang/scripts/test-multiple-child-folders-package/model/C.java
java.nio.file.NoSuchFileException: /home/leandro/dev/java/jbang/scripts/test-multiple-child-folders-package/model/C.java
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
...
at dev.jbang.cli.BaseScriptCommand.resolveSOURCESRecursively(BaseScriptCommand.java:188)
at dev.jbang.cli.BaseScriptCommand.prepareScript(BaseScriptCommand.java:158)
at dev.jbang.cli.Run.doCall(Run.java:53)
at …
```

fix: update base path when resolving //SOURCES

---

readme.adoc
src/main/java/dev/jbang/AliasUtil.java
src/test/java/dev/jbang/cli/TestCatalogNearest.java

fix: aliases no longer look for master, asks for HEAD instead Fixes #485

---

src/main/java/dev/jbang/ScriptResource.java
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/main/java/dev/jbang/cli/Run.java
src/test/java/dev/jbang/TestScript.java
src/test/java/dev/jbang/TestSourcesRecursivelyMultipleFiles.java

Today jbang only will create a new jar if the main class was changed.
This flag enables force the update.

feat: force update. Add -f --fresh flag

---

readme.adoc

docs: Various minor changes to sentences.

---

src/main/scripts/jbang.cmd

Yeah, I know, this should have a test!

fix: Default JDK wasn't properly set on Windows

---

src/main/java/dev/jbang/Detector.java
src/test/java/dev/jbang/DependencyResolverTest.java

fix: jfxname magic property fixed on windows Fixes #526

---

readme.adoc

Just a small first contrib with a minor doc clarification about something I've run into when using jbang in a project.
PS: Hey @maxandersen I'd known about jbang since early days, but only today found a reason to actually play with it - it's so cool!

docs: Explain wrapper's .jbang/ and suggest to .gitignore it

---

itests/jbang-catalog.json
itests/run.feature
src/main/java/dev/jbang/FileRef.java
src/main/java/dev/jbang/Script.java
src/main/java/dev/jbang/URLRef.java
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/cli/Info.java
src/main/java/dev/jbang/cli/Run.java

fix: Fixed more instances of relative file handling

---

src/main/java/dev/jbang/JdkManager.java
src/main/java/dev/jbang/Settings.java
src/main/java/dev/jbang/UnpackUtil.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/Jbang.java
src/main/java/dev/jbang/cli/Setup.java
src/main/scripts/jbang
src/main/scripts/jbang.cmd
src/main/scripts/jbang.ps1
src/test/java/dev/jbang/DependencyResolverTest.java

It works fine on Linux.
But it's the Windows implementation I'm worried about, it's more complex because of the fact that we can't overwrite any files that are currently in use. So I had to come up with a ping-pong mechanism of handing execution over from one script to another. I haven't been able to test any of that because I don't have access to a Windows machine right now. So I will need help validating what I implemented (especially the powershell version is most likely incorrect).

Jbang setup

---

src/main/java/dev/jbang/cli/Setup.java

fix: jbang setup should gracefully fail on mising bash/zshrc

---

src/main/scripts/jbang.cmd
src/main/scripts/jbang.ps1

A couple of small but necessary fixes for zero-install on Windows

Fix zero-install

---

src/main/java/dev/jbang/cli/Edit.java
src/main/resources/build.qute.gradle
src/test/java/dev/jbang/cli/TestEdit.java

Minimal patch; DependencyUtils.resolveDependencies() needs a bigger refactor.

feat: minimal jitpack and //REPOS support in edit/live mode

---

src/main/java/dev/jbang/DependencyUtil.java

GAV running skipped the depedency cache due to how we first resolve non-transitively then afterwords with transitivity and not storing in cache that is now changed. You will still see two depedency reesolutons on first run; but second ones should be fast and not log extra.
Fixes #222
Couldn't come up with a good way of testing it but since it just reuse existing caching
with a prefix it is pretty well tested.

fix: use dependency cache when launching GAV. 

---

readme.adoc

docs: document app install/setup commnads

---

src/main/java/dev/jbang/Script.java
src/test/java/dev/jbang/TestScript.java

feat: // commands ignore // comments Fixes #567

---

src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/main/java/dev/jbang/cli/Edit.java
src/test/java/dev/jbang/cli/TestRun.java

fix: support urls with extension less files Fixes #568

---

src/main/java/dev/jbang/cli/App.java
src/test/java/dev/jbang/cli/TestApp.java

fix: Make `app install --force` work

---

src/main/java/dev/jbang/DependencyUtil.java

Cleans up repo alias to not have public final constants beyond the ones with special treatment. Fixes #610

fix: add sponge repo alias Cleans up repo alias to not have public final constants beyond the ones with special treatment. Fixes #610

---

src/main/java/dev/jbang/cli/App.java
src/test/java/dev/jbang/cli/TestApp.java

It would append to any existing files before but now overwrites.
Fixes #620

fix: `app install --force` now properly overwrites

---

src/main/java/dev/jbang/cli/App.java
src/main/java/dev/jbang/cli/Export.java
src/main/java/dev/jbang/cli/Jdk.java

feat: add --force to export

---

src/main/java/dev/jbang/cli/Run.java
src/test/java/dev/jbang/cli/TestRun.java

feat: enable assertations

---

readme.adoc
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/test/java/dev/jbang/cli/TestRun.java

should now treat `jbang .` as `jbang ./app.java` and any urls with `/` in end gets app.java added.
i.e. `jbang https://jbang.dev/` works :) 
note, `jbang https://github.com/jbangdev/jbang.dev/` does *not* currently work - not sure if should make that work...thoughts?

feat: add notion of default application

---

readme.adoc

documentation and samples to support editors on command line

support editors on command line

---

src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/BaseCommand.java

fix: fix some spotbugs warnings

---

src/main/java/dev/jbang/Util.java
src/main/scripts/jbang

Overrides https://github.com/jbangdev/jbang/pull/656

fix: do not fail on unrecognized OS like arm64 for new macs. should at least try run located java.

---

src/main/java/dev/jbang/cli/BaseCommand.java

PR is pretty straightforward. :-)

How to get help for a specific command

---

src/main/java/dev/jbang/cli/App.java
src/test/java/dev/jbang/cli/TestApp.java

feat: jbang app install --native

---

src/main/resources/settings.qute.json

See https://github.com/redhat-developer/vscode-java/issues/1664
```
jbang init --template=cli hello.java
jbang edit --open --live hello.java
```
Hover over picocli.CommandLine, see the Javadoc magically appear

feat: Automatically download sources in VS Code

---

src/test/java/dev/jbang/BaseTest.java
src/test/java/dev/jbang/TestUtil.java
src/test/java/dev/jbang/cli/TestEdit.java
src/test/java/dev/jbang/cli/TestRun.java

chore: clean up test setup and make it run in eclipse out-of-box

---

src/main/java/dev/jbang/Cache.java
src/main/java/dev/jbang/JdkManager.java
src/main/java/dev/jbang/ResourceRef.java
src/main/java/dev/jbang/ScriptSource.java
src/main/java/dev/jbang/Settings.java
src/main/java/dev/jbang/TemplateEngine.java
src/main/java/dev/jbang/TrustedSources.java
src/main/java/dev/jbang/Util.java
src/main/java/dev/jbang/cli/App.java
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/Cache.java
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/cli/Init.java
src/main/java/dev/jbang/cli/Trust.java
src/test/java/dev/jbang/TestScript.java
src/test/java/dev/jbang/cli/TestRun.java

Extracted out some code from Settings.... this also changes 80+% of files... but don't worry I can redo it pretty quickly if needed :sweat_smile:

Settings refactor

---

readme.adoc

Maven central alias readme fix

docs: maven central alias readme fix

---

build.gradle

Fixes #753
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

chore: exclude .idea folder from spotless xml check

---

readme.adoc

Add docs regarding AIX as a follow-on to adding the support in https://github.com/jbangdev/jbang/pull/755

Add AIX references in the documentation

---

src/main/java/dev/jbang/cli/App.java
src/test/java/dev/jbang/cli/TestApp.java

fix: have jbang app install GAV not use physical paths in script

---

readme.adoc

chore: mention -ti with docker command for those who might need console input

---

itests/helloworld.java
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/Info.java
src/main/java/dev/jbang/cli/Run.java
src/main/java/dev/jbang/source/JarSource.java
src/main/java/dev/jbang/source/RunContext.java
src/main/java/dev/jbang/source/ScriptSource.java
src/main/java/dev/jbang/source/Source.java
src/test/java/dev/jbang/cli/TestRun.java

fix: Not duplicating or misquoting java options anymore

---

src/main/java/dev/jbang/catalog/Alias.java
src/main/java/dev/jbang/catalog/Catalog.java
src/main/java/dev/jbang/catalog/Template.java

Two issues:
- Information about templates and catalog refs wasn't being preserved
- @-naming wasn't implemented for referring to remote templates

Make remote templates work

---

src/main/java/dev/jbang/cli/Init.java
src/test/java/dev/jbang/cli/TestInit.java

fix: Fixed template init naming validation

---

src/test/java/dev/jbang/cli/TestRun.java

chore: testing for jfr output.

---

itests/export.feature
itests/jbang-catalog.json
readme.adoc
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/BaseScriptCommand.java
src/main/java/dev/jbang/cli/BaseScriptDepsCommand.java
src/main/java/dev/jbang/cli/Build.java
src/main/java/dev/jbang/cli/DependencyInfoMixin.java
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/cli/Export.java
src/main/java/dev/jbang/cli/ExportMixin.java
src/main/java/dev/jbang/cli/Info.java
src/main/java/dev/jbang/cli/Run.java
src/main/java/dev/jbang/source/JarSource.java
src/main/java/dev/jbang/source/RunContext.java
src/main/java/dev/jbang/source/ScriptSource.java
src/main/java/dev/jbang/source/Source.java
src/main/resources/pom.qute.xml
src/test/java/dev/jbang/cli/TestExport.java
src/test/java/dev/jbang/cli/TestRun.java

this adds a `--mavenpublish` which will generate .jar / .pom
with group, artifact and version.
draft, as for now im not happy with the defaults of group and version and that i must use --fresh as otherwise 
pom.xml generation fails every second time - somehow classpath are not accessible.

feat: add mavenrepo export option

---

src/main/java/dev/jbang/cli/App.java

fix: jbang update not working if update already downloaded old update. fixes #809

---

src/main/scripts/jbang.cmd

fix: Invalid comment in jbang.cmd

---

itests/helloworld.java
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/cli/Run.java
src/test/java/dev/jbang/cli/TestRun.java

fix: Make sure java opts get quoted properly in jar MANIFEST

---

src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/source/ScriptSource.java
src/main/java/dev/jbang/util/Util.java
src/test/java/dev/jbang/cli/TestEdit.java

needed this for qute templates and realized they were not editable....seem to easy but I think this is
all it takes :)
in draft as still need tests ...

feat: //FILES included in ide project Fixes #749

---

readme.adoc

chore: bump maven plugin to 0.0.7

---

src/main/java/dev/jbang/Settings.java
src/main/java/dev/jbang/util/Util.java
src/main/scripts/jbang

feat: Support Alpine Linux

---

itests/catalog.feature
itests/run.feature
readme.adoc
src/main/java/dev/jbang/catalog/Catalog.java
src/main/java/dev/jbang/catalog/CatalogRef.java
src/main/java/dev/jbang/catalog/CatalogUtil.java
src/main/java/dev/jbang/cli/Alias.java
src/main/java/dev/jbang/cli/Catalog.java
src/main/java/dev/jbang/cli/Template.java
src/main/java/dev/jbang/util/ConsoleOutput.java
src/test/java/dev/jbang/cli/TestApp.java
src/test/java/dev/jbang/cli/TestCatalog.java

Implemented all items from issue #854

---

itests/app-win.feature
itests/app.feature
src/main/java/dev/jbang/cli/App.java
src/test/java/dev/jbang/cli/TestApp.java

It messes with arguments containing spaces

fix: Don't use `eval` in app scripts

---

src/main/scripts/jbang.ps1

<!- 
Thanks for submitting your Pull Request!
Please delete this text, and add description of the topic solved by this PR.
To make releases as automated as possible we use conventional commits formats.
Thus commits and pull-requests titles should before merge follow the Conventional Commits spec.
Details in https://github.com/zeke/semantic-pull-requests
If in doubt then open the pull-request and we'll help you - Thank you!
-->

fixes #932

---

src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/util/TemplateEngine.java
src/main/resources/build.qute.gradle
src/test/java/dev/jbang/cli/TestEdit.java
src/test/java/dev/jbang/cli/TestEditWithPom.java

fix: @pom dependencies handled when using jbang edit

---

src/main/java/dev/jbang/cli/Edit.java
src/test/java/dev/jbang/cli/TestEdit.java

fix: avoid jitpack gets added unnecessarily

---

src/main/java/dev/jbang/cli/App.java

fix: Update correct bash file on Mac

---

docs/modules/ROOT/pages/usage.adoc
itests/run.feature
jreleaser.yml
src/jreleaser/distributions/jbang/docker/Dockerfile.tpl
src/jreleaser/templates/article/blogpost.adoc
src/main/java/dev/jbang/source/ResourceRef.java
src/main/java/dev/jbang/util/Util.java

if you really want .jsh you can use `--jsh`

enable jsh by detecting main on stdin input.

---

src/main/java/dev/jbang/cli/Alias.java
src/main/java/dev/jbang/cli/Run.java
src/test/java/dev/jbang/cli/TestRun.java

Both for #418 and to fix the flag used by `alias add`

feat: add `--java-options`

---

src/main/java/dev/jbang/cli/App.java
src/main/java/dev/jbang/util/Util.java

We're not trying to resolve new version downloads from cache anymore
Fixes #990

fix: Fixed version updates

---

src/main/java/dev/jbang/catalog/Catalog.java
src/main/java/dev/jbang/cli/Catalog.java

fix: 404s won't fail catalog list/update commands anymore

---

src/main/java/dev/jbang/cli/App.java
src/main/java/dev/jbang/cli/Version.java

[fix] Make sure `version --update` works on Windows

---

src/main/java/dev/jbang/cli/Init.java
src/test/java/dev/jbang/cli/TestInit.java
src/test/java/dev/jbang/cli/TestTemplate.java

fix: `baseName` is no longer ambiguous

---

src/main/scripts/jbang

fix: Fixed download URL in `jbang` script

---

src/main/java/dev/jbang/util/VersionChecker.java

fix: Not checking for new version on first run anymore

---

src/main/scripts/jbang.cmd
src/main/scripts/jbang.ps1

Fixes #878
The update for Windows still wasn't 100% correct.
This time manually tested by faking a newer version.
(Tried putting that into a test but that was much harder than expected so gave up)

fix: Now really fixed updating on Windows

---

itests/init.feature
itests/templates/test.java.qute
src/main/java/dev/jbang/cli/Init.java

Add itest for issue #1019
Fixes: 1032, 1034

fix: Add itest for issue #1019

---

src/main/java/dev/jbang/cli/BaseBuildCommand.java

in cleaing up properties handling we missed that jbang build integration,
especially quarkus, relied on properties being in system properties.
Fix for now is to set system properties temporariliy before jbang integration
called and then restored again.
Fixes #1058

fix: restore system level properties for build integration.

---

itests/init.feature
src/main/java/dev/jbang/cli/Init.java

fix: Regression regarding issue 1019 (Issue #1056)

fix: Regression regarding issue 1019

---

build.gradle

See https://github.com/ajoberstar/grgit/releases/tag/4.1.1

build: Fixed build for Java 8

---

src/main/java/dev/jbang/cli/App.java
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/Jdk.java
src/main/java/dev/jbang/cli/Run.java
src/main/java/dev/jbang/util/Util.java
src/main/scripts/jbang
src/main/scripts/jbang.cmd
src/main/scripts/jbang.ps1
src/test/java/dev/jbang/BaseTest.java

fix: `jdk` now works properly on bash in Windows

---

src/main/java/dev/jbang/cli/Catalog.java
src/main/java/dev/jbang/util/Util.java

fix: `catalog update` doesn't refresh cache

---

src/main/java/dev/jbang/cli/BaseBuildCommand.java

fix: verbose will now report why build is happening

---

src/main/java/dev/jbang/catalog/Catalog.java
src/main/java/dev/jbang/cli/App.java
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/Catalog.java
src/main/java/dev/jbang/cli/DependencyInfoMixin.java
src/main/java/dev/jbang/cli/Export.java
src/main/java/dev/jbang/cli/Info.java
src/main/java/dev/jbang/cli/Init.java
src/main/java/dev/jbang/cli/JBang.java
src/main/java/dev/jbang/cli/Run.java
src/main/java/dev/jbang/dependencies/DependencyUtil.java
src/main/java/dev/jbang/net/TrustedSources.java
src/main/java/dev/jbang/source/GroovyScriptSource.java
src/main/java/dev/jbang/source/MarkdownScriptSource.java
src/main/java/dev/jbang/source/ScriptSource.java
src/main/java/dev/jbang/util/Util.java
src/test/java/dev/jbang/cli/TestInit.java
src/test/java/dev/jbang/dependencies/DependencyResolverTest.java
src/test/java/dev/jbang/source/TestSourcesMultipleSomeMissingFiles.java

Various minor changes to improve readability.
CC @maxandersen

Miscellaneous code cleanup

---

itests/deps.jsh
itests/jsh.feature
src/main/java/dev/jbang/cli/Run.java
src/test/java/dev/jbang/cli/TestRun.java

fix: fixes running Jshell script with //DEPS

---

settings.gradle

This fixes this security issue: https://security.gradle.com/advisory/2021-11

fix: upgrade to latest gradle plugin

---

src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/source/resolvers/RemoteResourceResolver.java

fixes #1260 by making default choice to cancel so trust nor edit won't install ide by default.

fix: do not trust nor install editor by default

---

src/main/java/dev/jbang/Configuration.java
src/main/java/dev/jbang/catalog/Catalog.java
src/main/java/dev/jbang/source/ResourceRef.java
src/main/java/dev/jbang/source/ResourceResolver.java
src/main/java/dev/jbang/source/RunContext.java
src/main/java/dev/jbang/source/Source.java
src/main/java/dev/jbang/source/resolvers/AliasResourceResolver.java

This now only works for `--sources` (`-s`) on the command line, not for `//SOURCES` which needs more changes.

feat: Made `--sources script@repo` work

---

docs/modules/ROOT/pages/installation.adoc

Minor updates to the installation pre-instruction section.

docs: Minor updates to installation pre-instructions

---

src/main/java/dev/jbang/source/resolvers/RemoteResourceResolver.java
src/main/java/dev/jbang/util/Util.java

feat: don't ask for trust when resource is cached

---

src/main/java/dev/jbang/source/resolvers/ClasspathResourceResolver.java

fix: don't copy classpath files more than once

---

build.gradle
itests/config.feature
itests/karate-config.js

This should fix problems with `config set`.
Fixes #1299

fix: updated to latest java-properties

---

src/main/java/dev/jbang/cli/JBang.java

Update copyright year to 2022

---

.github/workflows/ci-build.yml
build.gradle
src/main/java/dev/jbang/spi/IntegrationManager.java

hopefully fixes #1316 by making gson behave better.

fix: upgrade gson to avoid breaking quarkus integration

---

itests/classpath_log_grab_with_ranges.java
src/test/java/dev/jbang/cli/TestRun.java

Add the example discussed in https://github.com/jbangdev/jbang/issues/1267#issuecomment-1054348159 to the test suite.

test: add a test with a version range

---

src/main/java/dev/jbang/cli/Run.java
src/main/java/dev/jbang/source/RunContext.java
src/main/java/dev/jbang/source/generators/JarCmdGenerator.java
src/test/java/dev/jbang/cli/TestRun.java

Follow up on this discussion:
https://github.com/jbangdev/jbang/pull/1348#discussion_r862709540

Allow no main if not non-interactive(batch) run

---

src/main/java/dev/jbang/dependencies/DependencyUtil.java
src/main/java/dev/jbang/dependencies/MavenRepo.java
src/test/java/dev/jbang/dependencies/DependencyResolverTest.java

feat: Set Maven update policy to ALWAYS when --fresh is used

---

src/main/java/dev/jbang/cli/Run.java
src/main/java/dev/jbang/source/RunContext.java
src/main/java/dev/jbang/source/generators/JarCmdGenerator.java

As requested by @quintesse :
https://github.com/jbangdev/jbang/pull/1355#pullrequestreview-958936848

refactor: turned `isRunCommand` into `isMainRequired`

---

src/main/java/dev/jbang/source/RunContext.java
src/main/java/dev/jbang/util/Util.java
src/test/java/dev/jbang/cli/TestRun.java
src/test/java/dev/jbang/util/TestUtil.java

Besides that it's now also possible to use absolute paths together
with globbing.

fix: can now use globbing for `--sources`

---

src/main/java/dev/jbang/cli/Alias.java
src/main/java/dev/jbang/source/ResourceResolver.java
src/main/java/dev/jbang/source/RunContext.java
src/main/java/dev/jbang/source/resolvers/AliasResourceResolver.java
src/test/java/dev/jbang/cli/TestAlias.java
src/test/java/dev/jbang/cli/TestRun.java

fix: make aliases work with --repos

---

src/main/java/dev/jbang/source/sources/MarkdownSource.java

refactor: fix typo in MarkdownSource.java

---

docs/modules/ROOT/pages/integration.adoc

docs: Updating Integration documentation (#1380)

---

src/main/scripts/jbang
src/main/scripts/jbang.cmd
src/main/scripts/jbang.ps1

fix: fix problem with JDK paths containing spaces

---

src/main/scripts/jbang.ps1

docs: minor update to PS1 script docs

---

src/main/scripts/jbang.cmd

fix: remove unnecessary quotations for java binary

---

src/main/java/dev/jbang/cli/App.java
src/main/scripts/jbang.ps1
src/test/java/dev/jbang/cli/TestApp.java

fix: Add splatting for passing arguments in Powershell scripts

---

build.gradle
src/main/java/dev/jbang/dependencies/DependencyResolver.java
src/main/java/dev/jbang/dependencies/DependencyUtil.java
src/main/java/dev/jbang/source/RunContext.java
src/test/java/dev/jbang/BaseTest.java
src/test/java/dev/jbang/source/TestRunContext.java
src/test/resources/junit-platform.properties

fix: now correctly handling duplicate repos

---

src/jreleaser/distributions/jbang/docker/README.md.tpl

fix: typo in README.md.tpl

---

itests/echo.bat
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/source/builders/BaseBuilder.java
src/main/java/dev/jbang/source/generators/BaseCmdGenerator.java
src/main/java/dev/jbang/util/CommandBuffer.java
src/main/java/dev/jbang/util/Util.java
src/test/java/dev/jbang/cli/TestRun.java
src/test/java/dev/jbang/util/TestCommandBuffer.java

Fixed passing arguments to .bat files on Windows

---

src/main/java/dev/jbang/cli/Info.java
src/main/java/dev/jbang/source/Project.java
src/test/java/dev/jbang/cli/TestInfo.java

fix: Fixed NPE when running `info` on a JAR file

---

src/main/java/dev/jbang/Configuration.java
src/main/java/dev/jbang/cli/Alias.java
src/main/java/dev/jbang/cli/App.java
src/main/java/dev/jbang/cli/Catalog.java
src/main/java/dev/jbang/cli/Config.java
src/main/java/dev/jbang/cli/FormatMixin.java
src/main/java/dev/jbang/cli/Jdk.java
src/main/java/dev/jbang/cli/Template.java
src/main/java/dev/jbang/cli/Trust.java
src/test/java/dev/jbang/cli/TestConfig.java
src/test/java/dev/jbang/cli/TestJdk.java

feat: Added `--format=json` flag to `list` commands

---

src/main/java/dev/jbang/cli/Export.java
src/main/java/dev/jbang/dependencies/DependencyUtil.java
src/main/java/dev/jbang/dependencies/MavenCoordinate.java
src/main/java/dev/jbang/source/Code.java
src/main/java/dev/jbang/source/Jar.java
src/main/java/dev/jbang/source/Project.java
src/main/java/dev/jbang/source/Source.java
src/main/java/dev/jbang/source/builders/BaseBuilder.java
src/test/java/dev/jbang/cli/TestExport.java

fix: use `//GAV` for `export mavenrepo`

---

itests/with space/helloworld.java
src/main/java/dev/jbang/cli/App.java
src/test/java/dev/jbang/cli/TestApp.java

fix: fixed "app install" using path with spaces

---

src/main/java/dev/jbang/dependencies/ArtifactResolver.java
src/main/java/dev/jbang/dependencies/MavenCoordinate.java
src/test/java/dev/jbang/dependencies/DependencyResolverTest.java

fix: the Aether resolver now uses packing types

---

docs/modules/ROOT/pages/debugging.adoc
src/main/java/dev/jbang/catalog/Alias.java
src/main/java/dev/jbang/catalog/Catalog.java
src/main/java/dev/jbang/catalog/CatalogUtil.java
src/main/java/dev/jbang/cli/Alias.java
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/BuildMixin.java
src/main/java/dev/jbang/cli/Export.java
src/main/java/dev/jbang/cli/Run.java
src/main/java/dev/jbang/source/ProjectBuilder.java
src/main/java/dev/jbang/source/buildsteps/CompileBuildStep.java
src/test/java/dev/jbang/cli/TestAlias.java
src/test/java/dev/jbang/cli/TestAliasNearest.java
src/test/java/dev/jbang/cli/TestAliasNearestWithBaseRef.java
src/test/java/dev/jbang/cli/TestRun.java
src/test/java/dev/jbang/source/TestBuilder.java

feat: enable -g by default + allow -g=vars,lines,source,none

---

.github/workflows/ci-build.yml

See: https://github.com/gradle/wrapper-validation-action
Ensure the integrity of gradle wrapper jar.

chore: Official Gradle Wrapper Validation Action

---

build.gradle

This fixes a problem with spotless on Windows

fix: upgraded to latest spotless

---

docs/modules/ROOT/pages/faq.adoc

Adding two articles I have authored for JBang

Added two articles to the Faqs

---

src/main/java/dev/jbang/cli/App.java
src/main/java/dev/jbang/cli/Info.java
src/main/java/dev/jbang/cli/Jdk.java
src/main/java/dev/jbang/net/JdkManager.java
src/main/java/dev/jbang/net/jdkproviders/JBangJdkProvider.java
src/main/java/dev/jbang/util/Util.java
src/test/java/dev/jbang/cli/TestJdk.java
src/test/java/dev/jbang/cli/TestRun.java

Fix problem with broken JDK links

---

itests/echo.ps1
src/main/java/dev/jbang/util/CommandBuffer.java
src/test/java/dev/jbang/util/TestCommandBuffer.java

Turns out the regular expression was formatted wrong.

fix: fixed issue with PowerShell quoting

---

src/main/java/dev/jbang/cli/JBang.java

Upgrade (c) from 2022 to 2023

---

docs/modules/ROOT/pages/usage.adoc
src/main/java/dev/jbang/util/Util.java
src/main/scripts/jbang.ps1

fix: Symbolic link permission issues on Windows

---

src/main/java/dev/jbang/Settings.java
src/main/scripts/jbang
src/main/scripts/jbang.cmd
src/main/scripts/jbang.ps1

feat: set Java 17 as the default for new installations

---

docs/modules/ROOT/pages/running.adoc
src/main/java/dev/jbang/cli/Run.java
src/main/java/dev/jbang/util/Util.java
src/test/java/dev/jbang/cli/TestRun.java

feat: added support for remote-file arguments

---

src/main/java/dev/jbang/catalog/Alias.java
src/main/java/dev/jbang/catalog/Catalog.java
src/main/java/dev/jbang/catalog/CatalogUtil.java
src/main/java/dev/jbang/cli/Alias.java
src/main/java/dev/jbang/cli/BaseBuildCommand.java
src/main/java/dev/jbang/cli/BuildMixin.java
src/main/java/dev/jbang/cli/Run.java
src/main/java/dev/jbang/cli/RunMixin.java
src/main/java/dev/jbang/source/CmdGeneratorBuilder.java
src/main/java/dev/jbang/source/ProjectBuilder.java
src/main/java/dev/jbang/util/Util.java
src/test/java/dev/jbang/TestConfiguration.java
src/test/java/dev/jbang/cli/TestAlias.java
src/test/java/dev/jbang/cli/TestAliasNearest.java
src/test/java/dev/jbang/cli/TestAliasNearestWithBaseRef.java
src/test/java/dev/jbang/cli/TestArguments.java
src/test/java/dev/jbang/cli/TestRun.java
src/test/java/dev/jbang/cli/TestTemplate.java
src/test/java/dev/jbang/source/TestBuilder.java

Added most remaining run flags to aliases.
Finished implementing --manifest option.

feat: many run flags for aliases and `--manifest`

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Wondering if we shouldn't make sure we're on the latest version of all the build tools. So far things seem to work.

Update to gradle 8

---

src/main/java/dev/jbang/Settings.java
src/main/java/dev/jbang/cli/Info.java
src/main/java/dev/jbang/cli/Run.java
src/main/java/dev/jbang/dependencies/ArtifactInfo.java
src/main/java/dev/jbang/dependencies/ModularClassPath.java
src/main/java/dev/jbang/source/AppBuilder.java
src/main/java/dev/jbang/source/CmdGeneratorBuilder.java
src/main/java/dev/jbang/source/Project.java
src/main/java/dev/jbang/source/TagReader.java
src/main/java/dev/jbang/source/buildsteps/CompileBuildStep.java
src/main/java/dev/jbang/source/generators/JarCmdGenerator.java
src/main/java/dev/jbang/source/generators/JshCmdGenerator.java
src/main/java/dev/jbang/util/JarUtil.java
src/main/java/dev/jbang/util/JavaUtil.java
src/main/java/dev/jbang/util/ModuleUtil.java
src/main/java/dev/jbang/util/Util.java
src/main/java9/dev/jbang/util/ModuleUtil9.java
src/main/resources/module-info.qute.java
src/test/java/dev/jbang/BaseTest.java
src/test/java/dev/jbang/cli/TestAliasNearest.java
src/test/java/dev/jbang/cli/TestAliasNearestWithBaseRef.java
src/test/java/dev/jbang/cli/TestAliasWithBaseRef.java
src/test/java/dev/jbang/cli/TestCatalog.java
src/test/java/dev/jbang/cli/TestCatalogNearest.java
src/test/java/dev/jbang/cli/TestRun.java
src/test/java/dev/jbang/cli/TestTemplate.java
src/test/java/dev/jbang/source/TestModule.java

Moved all module fixes from #1593 to this PR leaving that one as a clean feature PR.

fix: Module fixes

---

build.gradle
docs/modules/ROOT/pages/editing.adoc
docs/modules/ROOT/pages/organizing.adoc
docs/modules/cli/pages/jbang.adoc
itests/edit.feature
src/main/java/dev/jbang/cli/Edit.java
src/main/java/dev/jbang/cli/Init.java
src/main/java/dev/jbang/cli/ScriptMixin.java
src/test/java/dev/jbang/cli/TestEdit.java
src/test/java/dev/jbang/cli/TestEditLocate.java
src/test/java/dev/jbang/dependencies/DependencyResolverTest.java

Fixes #462
work in progress but last time I lost it by accidental delete thus
opening this now :)

feat: jbang direct edit

---

src/main/java/dev/jbang/cli/Init.java
src/main/java/dev/jbang/util/VersionChecker.java

feat: jbang init --edit to have editor open directly

---

src/main/java/dev/jbang/source/TagReader.java
src/test/java/dev/jbang/source/TestModule.java

fix: trim trailing whitespaces in //MODULE directive

---

src/main/java/dev/jbang/cli/Jdk.java
src/test/java/dev/jbang/cli/TestJdk.java

Fix: two fixes for `java-env`

---

src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java

fix: don't try resolving implicit catalogs for URLs

---

src/main/java/dev/jbang/cli/Export.java
src/test/java/dev/jbang/cli/TestExport.java

fix: export will now create missing output folders

---

src/main/java/dev/jbang/util/ConsoleInput.java

fix: Fixes NPE when running in container

---

src/main/java/dev/jbang/net/GroovyManager.java
src/main/java/dev/jbang/net/KotlinManager.java
src/main/java/dev/jbang/source/sources/GroovySource.java

- Update to Groovy default version to 4.0.14
- Support Groovy 5
- Update to Kotlin default version 1.8.22

chore: some changes for Groovy and Kotlin: Groovy default version to 4, support Groovy 5

---

src/main/java/dev/jbang/catalog/ImplicitCatalogRef.java

fix: support branch references with slashes in the ref name.

---

src/main/java/dev/jbang/catalog/Alias.java
src/main/java/dev/jbang/catalog/Catalog.java
src/main/java/dev/jbang/catalog/CatalogRef.java
src/main/java/dev/jbang/catalog/Template.java

feat: extended syntax for catalog references

---

src/main/java/dev/jbang/cli/App.java
src/main/java/dev/jbang/cli/BuildMixin.java
src/main/java/dev/jbang/cli/DependencyInfoMixin.java
src/main/java/dev/jbang/cli/JBang.java
src/main/java/dev/jbang/cli/JdkProvidersMixin.java
src/main/java/dev/jbang/cli/NativeMixin.java
src/main/java/dev/jbang/cli/RunMixin.java
src/main/java/dev/jbang/cli/ScriptMixin.java

feat: allow setting build/run options for `app install`

---

src/main/java/dev/jbang/source/TagReader.java
src/test/java/dev/jbang/source/TestTagReader.java

fix: taking tabs into account as seprator for tag values

---

src/main/java/dev/jbang/cli/JBang.java

Upgrade (c) to 2024 in CLI

---

itests/export.feature
src/main/java/dev/jbang/cli/Export.java

when usiing export portable --force was not being honored for individual jars in lib folder. this fixes that + adds actual test.

fix: export portable --force now works

---

docs/modules/ROOT/pages/organizing.adoc

Description: suggestion to make a section in `File Organization` more readable.

docs: Update organizing.adoc

---

src/main/java/dev/jbang/source/sources/MarkdownSource.java
src/test/java/dev/jbang/cli/TestRun.java

fix: Markdown files now handled properly on Windows

---

src/main/resources/init-qrest.java.qute

Hi,
This PR updates the qrest template with the latest quarkus version and also replaces javax package import with jakarta
Best Regards :)

Update and fix qrest cute template

---

src/main/java/dev/jbang/cli/JBang.java
src/main/java/dev/jbang/cli/Run.java

better document default command.

fix: document default command better

---

build.gradle

See https://github.com/jbangdev/jbang/pull/1866#issuecomment-2479868653

fix: fixes `InaccessibleObjectException` in tests on JDK 17+

---

.justfile
jreleaser.yml
src/main/java/dev/jbang/util/Util.java
src/test/java/dev/jbang/cli/TestRun.java

enables: `jbang https://bsky.app/profile/maxandersen.xam.dk/post/3lb34ijrdas2g`

feat: support running bsky posts

---

docs/modules/ROOT/pages/faq.adoc

See https://github.com/google//issues/1215 and https://github.com/google/google-java-format/issues/1214.

docs: Add links to relevant google-java-format issues to FAQ

---

docs/modules/ROOT/pages/running.adoc

as discussed on https://github.com/enola-dev/enola/pull/974#discussion_r1899255367

docs: Add //PREVIEW

---

docs/modules/ROOT/pages/faq.adoc

As discussed in https://github.com/google/google-java-format/issues/1214.
@maxandersen merge?

docs: Clarify further why normal shebang is really not recommended

---

docs/modules/ROOT/pages/integration.adoc

Documents https://github.com/jbangdev/jbang/pull/1875
See https://github.com/jbangdev/jbang/issues/1776, or https://github.com/orgs/jbangdev/discussions/1774#discussioncomment-11761212

docs: Add "Disable integrations" section

---

.sdkmanrc

chore: install Java 11 via SDKMAN

---

src/main/resources/init-qcli.java.qute
src/main/resources/init-qmetrics.java.qute
src/main/resources/init-qrest.java.qute
src/main/resources/init-readme.md.qute

fix: update templates

---

src/main/java/dev/jbang/cli/Export.java
src/main/resources/export-build.qute.gradle

fix: export gradle, add support for Groovy and Kotlin projects

---

src/main/resources/export-build.qute.gradle

fix: export gradle, add mavenLocal()

---

src/main/resources/export-pom.qute.xml

Removed lines that got committed by accident

fix: maven build template for export

---

.sdkmanrc

Set Gradle=8.9 and Java=11.0.26

chore(deps): sdkman, update java to 11.0.26-tem

---

src/main/java/dev/jbang/cli/JBang.java

chore: Upgrade (c) year to 2025

---

src/it/java/dev/jbang/it/CacheIT.java
src/main/java/dev/jbang/cli/Cache.java

fix: "jbang cache clear" deleting Kotlin and Groovy SDKs by default

---

docs/modules/ROOT/pages/installation.adoc

Update maven plugin to 0.0.8 which is the latest release

(doc) - Update maven plugin to 0.0.8 which is the latest release

---

src/main/java/dev/jbang/source/resolvers/RemoteResourceResolver.java

Fixes https://github.com/jbangdev/jbang/issues/2130

chore: Add reference to output

---

renovate.json
src/main/resources/dist/maven/update-version.sh

fix: renovate[bot] should ignore major version updates to wrappers for maven and gradle

---

gradle/wrapper/gradle-wrapper.properties

chore(deps): upgrade Gradle to 8.14.3

---

build.gradle
src/main/java/dev/jbang/cli/Completion.java

- **feat: fish completion**
- **feat: fish completion (forked while waiting for picocli)**
a version of #2195 which copies the picocli code into jbang - once picocli releases we can use it ...or keep this if they dont

fish completion using copy of picocli pr

---

src/main/java/dev/jbang/util/Util.java

fix: avoid java in user agent

---

itests/integrations/integration.java
itests/integrations/main.java
src/it/java/dev/jbang/it/IntegrationIT.java
src/main/java/dev/jbang/source/buildsteps/IntegrationBuildStep.java
src/main/java/dev/jbang/spi/IntegrationManager.java

Null values were improperly passed as "null" string. This is now fixed.
Plus some additional minor changes to make testing a bit easier/possible.
Fixes #2236

fix: properly pass directives to integration
